// <auto-generated />
using System;
using Gymmin.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gymmin.Api.Data.Migrations
{
    [DbContext(typeof(GymminDbContext))]
    [Migration("20260715203636_AddEmailVerification")]
    partial class AddEmailVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Gymmin.Api.Data.AiCreditAccountEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("AiCreditAccounts", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.AiCreditPurchaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AcknowledgementState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConsumptionState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleOrderId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseTokenHash")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseTokenLastChars")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedTransactionId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleOrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AiCreditPurchases", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.AiCreditTransactionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedJobId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedPurchaseId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IdempotencyKey");

                    b.HasIndex("RelatedJobId");

                    b.HasIndex("RelatedPurchaseId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Reason", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("UserId", "RelatedJobId", "Type")
                        .IsUnique();

                    b.HasIndex("UserId", "RelatedPurchaseId", "Type")
                        .IsUnique();

                    b.ToTable("AiCreditTransactions", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.BugReportEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminRespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Device")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailDeliveryError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailDeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailLastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailLeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailLeaseId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailNextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Screen")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("Status");

                    b.HasIndex("EmailDeliveryStatus", "EmailNextAttemptAt");

                    b.ToTable("BugReports", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.BugReportRewardTransactionEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AwardedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("BugReportId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BugReportId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BugReportRewardTransactions", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.PasswordResetTokenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedIpAddress")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserAchievementEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AchievementId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProgressAtUnlock")
                        .HasColumnType("REAL");

                    b.Property<string>("UnlockedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UnlockedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserAppUsageStatsEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalForegroundSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserAppUsageStats", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarContentType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarFileName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationCodeExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationSentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserFavoriteExerciseEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("UserFavoriteExercises", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserSessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserSettingsEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollapsedPanelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSetCount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultStageType")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultWeight")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultWorkoutExecutionMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultWorkoutTableOrientation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("IsAuthPanelDismissed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShowRestTimer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkoutRemindersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.WorkoutCreatorJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningEffort")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenRefundReason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenRefundedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenTransactionId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "JobType", "IdempotencyKey");

                    b.ToTable("WorkoutCreatorJobs", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.WorkoutEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientWorkoutId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerUpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkoutJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientWorkoutId")
                        .IsUnique();

                    b.HasIndex("UserId", "DeletedAt");

                    b.ToTable("Workouts", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.WorkoutSessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbandonedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSessionId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerUpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceWorkoutId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceWorkoutName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ClientSessionId")
                        .IsUnique();

                    b.HasIndex("UserId", "ClientUpdatedAt");

                    b.HasIndex("UserId", "DeletedAt");

                    b.HasIndex("UserId", "ServerUpdatedAt");

                    b.ToTable("WorkoutSessions", (string)null);
                });

            modelBuilder.Entity("Gymmin.Api.Data.AiCreditAccountEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("Gymmin.Api.Data.AiCreditAccountEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.AiCreditPurchaseEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.AiCreditTransactionEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.BugReportEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReporterUser");
                });

            modelBuilder.Entity("Gymmin.Api.Data.BugReportRewardTransactionEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.BugReportEntity", "BugReport")
                        .WithMany()
                        .HasForeignKey("BugReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BugReport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.PasswordResetTokenEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserAchievementEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserAppUsageStatsEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("Gymmin.Api.Data.UserAppUsageStatsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserFavoriteExerciseEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserSessionEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserSettingsEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("Gymmin.Api.Data.UserSettingsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.WorkoutCreatorJobEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.WorkoutEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.WorkoutSessionEntity", b =>
                {
                    b.HasOne("Gymmin.Api.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymmin.Api.Data.UserEntity", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
