import type { MuscleKey } from "./exercises";
import {
  advancedBackBodySvg,
  advancedFrontBodySvg,
  backBodySvg,
  frontBodySvg
} from "./bodySvg.generated";

export type BodyRegionMap = Record<string, MuscleKey>;

export { advancedBackBodySvg, advancedFrontBodySvg, backBodySvg, frontBodySvg };

export const frontBodyRegionMap: BodyRegionMap = {
  left_pectoralis_major: "chest",
  right_pectoralis_major: "chest",
  left_deltoid: "shoulders",
  right_deltoid: "shoulders",
  left_biceps_brachii: "biceps",
  right_biceps_brachii: "biceps",
  left_forearm_flexors: "forearm",
  right_forearm_flexors: "forearm",
  left_rectus_abdominis: "abs",
  right_rectus_abdominis: "abs",
  left_external_oblique: "obliques",
  right_external_oblique: "obliques",
  left_lower_oblique: "hips",
  right_lower_oblique: "hips",
  left_tensor_fasciae_latae: "abductors",
  right_tensor_fasciae_latae: "abductors",
  left_quadriceps_femoris: "quads",
  right_quadriceps_femoris: "quads",
  left_tibialis_anterior: "quads",
  right_tibialis_anterior: "quads"
};

export const backBodyRegionMap: BodyRegionMap = {
  lower_back_lumbar_region_center: "lowerBack",
  left_gastrocnemius_soleus: "calves",
  left_latissimus_dorsi: "lats",
  left_posterior_deltoid: "shoulders",
  left_posterior_thigh_lateral: "hamstrings",
  right_latissimus_dorsi: "lats",
  right_posterior_thigh_lateral: "hamstrings",
  right_lumbar_erector_spinae: "lowerBack",
  left_lumbar_erector_spinae: "lowerBack",
  left_hamstrings: "hamstrings",
  right_hamstrings: "hamstrings",
  right_gastrocnemius_soleus: "calves",
  left_gluteus_maximus_medius: "glutes",
  right_gluteus_maximus_medius: "glutes",
  right_trapezius_rhomboid_region: "traps",
  left_trapezius_rhomboid_region: "traps",
  right_forearm_posterior: "forearm",
  left_forearm_posterior: "forearm",
  right_posterior_deltoid: "shoulders",
  right_triceps_brachii: "triceps",
  left_triceps_brachii: "triceps",
  left_erector_spinae_thoracic: "lowerBack",
  right_erector_spinae_thoracic: "lowerBack",
  right_posterior_thigh_medial: "hamstrings",
  left_posterior_thigh_medial: "hamstrings",
  neck_and_upper_trapezius_center: "traps"
};

export const advancedFrontBodyRegionMap: BodyRegionMap = {
  left_pectoralis_major: "chest",
  right_pectoralis_major: "chest",
  left_deltoid: "shoulders",
  right_deltoid: "shoulders",
  left_biceps_brachii: "biceps",
  right_biceps_brachii: "biceps",
  left_forearm_flexors: "forearm",
  right_forearm_flexors: "forearm",
  left_rectus_abdominis: "abs",
  right_rectus_abdominis: "abs",
  left_external_oblique_upper: "obliques",
  left_external_oblique_lower: "obliques",
  right_external_oblique_upper: "obliques",
  right_external_oblique_lower: "obliques",
  right_external_oblique_upper_small_detail: "obliques",
  left_tensor_fasciae_latae: "abductors",
  right_tensor_fasciae_latae: "abductors",
  left_adductor_group: "adductors",
  right_adductor_group: "adductors",
  left_quadriceps_femoris: "quads",
  right_quadriceps_femoris: "quads"
};

export const advancedBackBodyRegionMap: BodyRegionMap = {
  left_latissimus_dorsi: "lats",
  right_latissimus_dorsi: "lats",
  left_latissimus_dorsi_upper_region: "lats",
  left_latissimus_dorsi_lower_region: "lats",
  right_latissimus_dorsi_upper_region: "lats",
  right_latissimus_dorsi_lower_region: "lats",
  left_posterior_deltoid: "shoulders",
  right_posterior_deltoid: "shoulders",
  left_triceps_brachii: "triceps",
  right_triceps_brachii: "triceps",
  left_triceps_brachii_long_head: "triceps",
  left_triceps_brachii_lateral_head: "triceps",
  left_triceps_brachii_medial_head: "triceps",
  right_triceps_brachii_long_head: "triceps",
  right_triceps_brachii_lateral_head: "triceps",
  right_triceps_brachii_medial_head: "triceps",
  left_forearm_posterior: "forearm",
  right_forearm_posterior: "forearm",
  left_trapezius_rhomboid_region: "traps",
  right_trapezius_rhomboid_region: "traps",
  left_upper_trapezius_neck_center: "traps",
  right_upper_trapezius_neck_center: "traps",
  left_trapezius_upper_fibers: "traps",
  right_trapezius_upper_fibers: "traps",
  left_trapezius_middle_fibers: "traps",
  right_trapezius_middle_fibers: "traps",
  left_trapezius_lower_fibers: "traps",
  right_trapezius_lower_fibers: "traps",
  neck_and_upper_trapezius_center: "traps",
  left_gluteus_maximus_medius: "glutes",
  right_gluteus_maximus_medius: "glutes",
  left_gluteus_maximus_upper_fibers: "glutes",
  left_gluteus_maximus_lower_fibers: "glutes",
  right_gluteus_maximus_upper_fibers: "glutes",
  right_gluteus_maximus_lower_fibers: "glutes",
  left_gluteus_medius_visible: "glutes",
  right_gluteus_medius_visible: "glutes",
  left_hamstrings: "hamstrings",
  right_hamstrings: "hamstrings",
  left_posterior_thigh_lateral: "hamstrings",
  right_posterior_thigh_lateral: "hamstrings",
  left_posterior_thigh_medial: "hamstrings",
  right_posterior_thigh_medial: "hamstrings",
  left_biceps_femoris: "hamstrings",
  right_biceps_femoris: "hamstrings",
  left_semitendinosus: "hamstrings",
  right_semitendinosus: "hamstrings",
  left_semimembranosus: "hamstrings",
  right_semimembranosus: "hamstrings",
  left_gastrocnemius_soleus: "calves",
  right_gastrocnemius_soleus: "calves",
  left_gastrocnemius_medial_head: "calves",
  left_gastrocnemius_lateral_head: "calves",
  right_gastrocnemius_medial_head: "calves",
  right_gastrocnemius_lateral_head: "calves",
  left_soleus: "calves",
  right_soleus: "calves",
  lower_back_lumbar_region_center: "lowerBack",
  left_lumbar_erector_spinae: "lowerBack",
  right_lumbar_erector_spinae: "lowerBack",
  left_erector_spinae_thoracic: "lowerBack",
  right_erector_spinae_thoracic: "lowerBack",
  left_erector_spinae_thoracic_iliocostalis: "lowerBack",
  left_erector_spinae_thoracic_longissimus: "lowerBack",
  left_erector_spinae_thoracic_spinalis: "lowerBack",
  right_erector_spinae_thoracic_iliocostalis: "lowerBack",
  right_erector_spinae_thoracic_longissimus: "lowerBack",
  right_erector_spinae_thoracic_spinalis: "lowerBack",
  left_erector_spinae_lumbar_iliocostalis: "lowerBack",
  left_erector_spinae_lumbar_longissimus: "lowerBack",
  left_erector_spinae_lumbar_spinalis: "lowerBack",
  right_erector_spinae_lumbar_iliocostalis: "lowerBack",
  right_erector_spinae_lumbar_longissimus: "lowerBack",
  right_erector_spinae_lumbar_spinalis: "lowerBack"
};
