import { resolveExerciseId } from "./exercises";

export type ExerciseImageAssetKey = string;

const exerciseImageAssetKeysById: Record<string, ExerciseImageAssetKey[]> = {
  "assisted-pull-up-machine": ["assisted-pull-up-machine/start", "assisted-pull-up-machine/end"],
  "banded-exercises-ab-twist-1": ["banded-exercises-ab-twist-1/start", "banded-exercises-ab-twist-1/end"],
  "banded-exercises-back-extension-2": ["banded-exercises-back-extension-2/start", "banded-exercises-back-extension-2/end"],
  "banded-exercises-bicycle-crunch-3": ["banded-exercises-bicycle-crunch-3/start", "banded-exercises-bicycle-crunch-3/end"],
  "banded-exercises-calf-raises-4": ["banded-exercises-calf-raises-4/start", "banded-exercises-calf-raises-4/end"],
  "banded-exercises-clam-shells-5": ["banded-exercises-clam-shells-5/start", "banded-exercises-clam-shells-5/end"],
  "banded-exercises-curl-6": ["banded-exercises-curl-6/start", "banded-exercises-curl-6/end"],
  "banded-exercises-deadbug-7": ["banded-exercises-deadbug-7/start", "banded-exercises-deadbug-7/end"],
  "bench-press-barbell-bench-press-76": ["bench-press-barbell-bench-press-76/start", "bench-press-barbell-bench-press-76/end"],
  "bench-press-barbell-floor-press-78": ["bench-press-barbell-floor-press-78/start", "bench-press-barbell-floor-press-78/end"],
  "bench-press-close-grip-barbell-bench-press-80": ["bench-press-close-grip-barbell-bench-press-80/start", "bench-press-close-grip-barbell-bench-press-80/end"],
  "bench-press-decline-dumbbell-bench-press-81": ["bench-press-decline-dumbbell-bench-press-81/start", "bench-press-decline-dumbbell-bench-press-81/end"],
  "bench-press-dumbbell-bench-press-82": ["bench-press-dumbbell-bench-press-82/start", "bench-press-dumbbell-bench-press-82/end"],
  "bench-press-dumbbell-floor-press-83": ["bench-press-dumbbell-floor-press-83/start", "bench-press-dumbbell-floor-press-83/end"],
  "bench-press-incline-barbell-bench-press-84": ["bench-press-incline-barbell-bench-press-84/start", "bench-press-incline-barbell-bench-press-84/end"],
  "bench-press-incline-dumbbell-bench-press-85": ["bench-press-incline-dumbbell-bench-press-85/start", "bench-press-incline-dumbbell-bench-press-85/end"],
  "bench-press-incline-smith-machine-bench-press-86": ["bench-press-incline-smith-machine-bench-press-86/start", "bench-press-incline-smith-machine-bench-press-86/end"],
  "bench-press-isometric-barbell-bench-press-87": ["bench-press-isometric-barbell-bench-press-87/start"],
  "bench-press-kettlebell-chest-press-88": ["bench-press-kettlebell-chest-press-88/start", "bench-press-kettlebell-chest-press-88/end"],
  "bench-press-neutral-grip-dumbbell-bench-press-89": ["bench-press-neutral-grip-dumbbell-bench-press-89/start", "bench-press-neutral-grip-dumbbell-bench-press-89/end"],
  "bench-press-neutral-grip-dumbbell-incline-bench-press-90": ["bench-press-neutral-grip-dumbbell-incline-bench-press-90/start", "bench-press-neutral-grip-dumbbell-incline-bench-press-90/end"],
  "bench-press-partial-lockout-92": ["bench-press-partial-lockout-92/start"],
  "bench-press-reverse-grip-barbell-bench-press-93": ["bench-press-reverse-grip-barbell-bench-press-93/start", "bench-press-reverse-grip-barbell-bench-press-93/end"],
  "bench-press-reverse-grip-incline-bench-press-94": ["bench-press-reverse-grip-incline-bench-press-94/start", "bench-press-reverse-grip-incline-bench-press-94/end"],
  "bench-press-smith-machine-bench-press-97": ["bench-press-smith-machine-bench-press-97/start", "bench-press-smith-machine-bench-press-97/end"],
  "bike-outdoor-bike-102": ["bike-outdoor-bike-102/start"],
  "bulgarian-split-squat": ["bulgarian-split-squat/start"],
  "calf-raise-donkey-calf-raise-108": ["calf-raise-donkey-calf-raise-108/start"],
  "cardio-bob-and-weave-circle-125": ["cardio-bob-and-weave-circle-125/start"],
  "cardio-cardio-core-crawl-126": ["cardio-cardio-core-crawl-126/end"],
  "cardio-double-under-127": ["cardio-double-under-127/start"],
  "cardio-jump-rope-jog-130": ["cardio-jump-rope-jog-130/start", "cardio-jump-rope-jog-130/end"],
  "cardio-jumping-jacks-131": ["cardio-jumping-jacks-131/start"],
  "cardio-split-jacks-133": ["cardio-split-jacks-133/start"],
  "cardio-squat-jacks-134": ["cardio-squat-jacks-134/start"],
  "cardio-triple-under-135": ["cardio-triple-under-135/start"],
  "carry-overhead-carry-156": ["carry-overhead-carry-156/end"],
  "chest-press": ["chest-press/start", "chest-press/end"],
  "chest-supported-machine-row": ["chest-supported-machine-row/start", "chest-supported-machine-row/end"],
  "chop-half-kneeling-rotational-reverse-chop-165": ["chop-half-kneeling-rotational-reverse-chop-165/start"],
  "chop-half-kneeling-stability-reverse-chop-167": ["chop-half-kneeling-stability-reverse-chop-167/start"],
  "chop-kneeling-rotational-reverse-chop-169": ["chop-kneeling-rotational-reverse-chop-169/start"],
  "chop-power-squat-chops-173": ["chop-power-squat-chops-173/start"],
  "chop-standing-split-rotational-reverse-chop-176": ["chop-standing-split-rotational-reverse-chop-176/start"],
  "chop-standing-stability-reverse-chop-177": ["chop-standing-stability-reverse-chop-177/start"],
  "core-alternating-slide-out-183": ["core-alternating-slide-out-183/end"],
  "core-cable-core-press-186": ["core-cable-core-press-186/start"],
  "core-half-turkish-get-up-193": ["core-half-turkish-get-up-193/start"],
  "core-hanging-l-sit-194": ["core-hanging-l-sit-194/start"],
  "core-inchworm-195": ["core-inchworm-195/start"],
  "core-l-sit-198": ["core-l-sit-198/start"],
  "core-open-knee-tucks-200": ["core-open-knee-tucks-200/start"],
  "core-ring-l-sit-202": ["core-ring-l-sit-202/start"],
  "core-toes-to-elbows-209": ["core-toes-to-elbows-209/start"],
  "crunch-cross-leg-reverse-crunch-240": ["crunch-cross-leg-reverse-crunch-240/start"],
  "crunch-flutter-kicks-246": ["crunch-flutter-kicks-246/start"],
  "crunch-hip-crossover-252": ["crunch-hip-crossover-252/start"],
  "crunch-hollow-rock-253": ["crunch-hollow-rock-253/start"],
  "crunch-incline-reverse-crunch-254": ["crunch-incline-reverse-crunch-254/start"],
  "crunch-knees-to-elbow-258": ["crunch-knees-to-elbow-258/start"],
  "crunch-leg-extensions-260": ["crunch-leg-extensions-260/start"],
  "crunch-mcgill-curl-up-262": ["crunch-mcgill-curl-up-262/end"],
  "crunch-reverse-crunch-267": ["crunch-reverse-crunch-267/start"],
  "crunch-reverse-crunch-on-a-bench-268": ["crunch-reverse-crunch-on-a-bench-268/start"],
  "crunch-reverse-curl-and-lift-269": ["crunch-reverse-curl-and-lift-269/start"],
  "crunch-seated-alternating-reverse-crunch-271": ["crunch-seated-alternating-reverse-crunch-271/start"],
  "curl-barbell-biceps-curl-326": ["curl-barbell-biceps-curl-326/start", "curl-barbell-biceps-curl-326/end"],
  "curl-barbell-reverse-wrist-curl-327": ["curl-barbell-reverse-wrist-curl-327/start"],
  "curl-behind-the-back-barbell-reverse-wrist-curl-329": ["curl-behind-the-back-barbell-reverse-wrist-curl-329/start"],
  "curl-cable-biceps-curl-331": ["curl-cable-biceps-curl-331/start", "curl-cable-biceps-curl-331/end"],
  "curl-dumbbell-biceps-curl-339": ["curl-dumbbell-biceps-curl-339/start", "curl-dumbbell-biceps-curl-339/end"],
  "curl-dumbbell-reverse-wrist-curl-342": ["curl-dumbbell-reverse-wrist-curl-342/start"],
  "curl-incline-dumbbell-biceps-curl-347": ["curl-incline-dumbbell-biceps-curl-347/start", "curl-incline-dumbbell-biceps-curl-347/end"],
  "curl-reverse-grip-wrist-curl-357": ["curl-reverse-grip-wrist-curl-357/start"],
  "deadlift-barbell-deadlift-371": ["deadlift-barbell-deadlift-371/start", "deadlift-barbell-deadlift-371/end"],
  "deadlift-barbell-straight-leg-deadlift-372": ["deadlift-barbell-straight-leg-deadlift-372/start"],
  "deadlift-dumbbell-deadlift-375": ["deadlift-dumbbell-deadlift-375/start"],
  "deadlift-dumbbell-straight-leg-deadlift-377": ["deadlift-dumbbell-straight-leg-deadlift-377/start"],
  "deadlift-kettlebell-deadlift-378": ["deadlift-kettlebell-deadlift-378/start"],
  "deadlift-kettlebell-sumo-deadlift-380": ["deadlift-kettlebell-sumo-deadlift-380/start"],
  "deadlift-romanian-deadlift-374": ["deadlift-romanian-deadlift-374/start", "deadlift-romanian-deadlift-374/end"],
  "deadlift-rotational-dumbbell-straight-leg-deadlift-383": ["deadlift-rotational-dumbbell-straight-leg-deadlift-383/start"],
  "deadlift-straight-leg-deadlift-395": ["deadlift-straight-leg-deadlift-395/start"],
  "deadlift-sumo-deadlift-391": ["deadlift-sumo-deadlift-391/start"],
  "deadlift-sumo-deadlift-high-pull-392": ["deadlift-sumo-deadlift-high-pull-392/start"],
  "deadlift-trap-bar-deadlift-393": ["deadlift-trap-bar-deadlift-393/start"],
  "deadlift-wide-grip-barbell-deadlift-394": ["deadlift-wide-grip-barbell-deadlift-394/start"],
  "elliptical-elliptical-396": ["elliptical-elliptical-396/start"],
  "flye-incline-dumbbell-flye-401": ["flye-incline-dumbbell-flye-401/start"],
  "flye-incline-reverse-flye-402": ["flye-incline-reverse-flye-402/start"],
  "flye-kneeling-rear-flye-404": ["flye-kneeling-rear-flye-404/start"],
  "glute-kickback": ["glute-kickback/start", "glute-kickback/end"],
  "hack-squat": ["hack-squat/start", "hack-squat/end"],
  "hip-abduction": ["hip-abduction/start", "hip-abduction/end"],
  "hip-adduction": ["hip-adduction/start", "hip-adduction/end"],
  "hip-raise-barbell-hip-thrust-on-floor-407": ["hip-raise-barbell-hip-thrust-on-floor-407/start"],
  "hip-raise-barbell-hip-thrust-with-bench-408": ["hip-raise-barbell-hip-thrust-with-bench-408/start"],
  "hip-raise-bridge-with-leg-extension-410": ["hip-raise-bridge-with-leg-extension-410/start"],
  "hip-raise-clam-bridge-411": ["hip-raise-clam-bridge-411/start"],
  "hip-raise-reverse-hip-raise-423": ["hip-raise-reverse-hip-raise-423/start"],
  "hip-stability-dead-bug-452": ["hip-stability-dead-bug-452/start", "hip-stability-dead-bug-452/end"],
  "hip-stability-hip-circles-455": ["hip-stability-hip-circles-455/start"],
  "hip-stability-quadruped-462": ["hip-stability-quadruped-462/start"],
  "hip-stability-standing-cable-hip-abduction-468": ["hip-stability-standing-cable-hip-abduction-468/start"],
  "hip-stability-standing-hip-abduction-469": ["hip-stability-standing-hip-abduction-469/start"],
  "hip-thrust": ["hip-thrust/start", "hip-thrust/end"],
  "hyperextension-bent-knee-reverse-hyperextension-494": ["hyperextension-bent-knee-reverse-hyperextension-494/start"],
  "hyperextension-kneeling-superman-499": ["hyperextension-kneeling-superman-499/start"],
  "hyperextension-medicine-ball-deadlift-to-reach-501": ["hyperextension-medicine-ball-deadlift-to-reach-501/start"],
  "hyperextension-plank-knee-tucks-505": ["hyperextension-plank-knee-tucks-505/start"],
  "hyperextension-side-step-506": ["hyperextension-side-step-506/start"],
  "hyperextension-superman-from-floor-510": ["hyperextension-superman-from-floor-510/start"],
  "lateral-raise-bar-muscle-up-538": ["lateral-raise-bar-muscle-up-538/start"],
  "lateral-raise-combo-shoulder-raise-543": ["lateral-raise-combo-shoulder-raise-543/start"],
  "lateral-raise-dumbbell-lateral-raise-545": ["lateral-raise-dumbbell-lateral-raise-545/start", "lateral-raise-dumbbell-lateral-raise-545/end"],
  "lateral-raise-overhand-grip-rear-lateral-raise-552": ["lateral-raise-overhand-grip-rear-lateral-raise-552/start"],
  "lateral-raise-ring-dip-554": ["lateral-raise-ring-dip-554/start"],
  "lateral-raise-ring-dip-kipping-555": ["lateral-raise-ring-dip-kipping-555/start"],
  "lateral-raise-underhand-grip-rear-lateral-raise-564": ["lateral-raise-underhand-grip-rear-lateral-raise-564/start"],
  "leg-curl-bar-good-morning-572": ["leg-curl-bar-good-morning-572/start"],
  "leg-curl-good-morning-573": ["leg-curl-good-morning-573/start"],
  "leg-curl-leg-curl-574": ["leg-curl-leg-curl-574/start", "leg-curl-leg-curl-574/end"],
  "leg-curl-seated-barbell-good-morning-575": ["leg-curl-seated-barbell-good-morning-575/start"],
  "leg-curl-split-barbell-good-morning-579": ["leg-curl-split-barbell-good-morning-579/start"],
  "leg-curl-staggered-stance-good-morning-581": ["leg-curl-staggered-stance-good-morning-581/start"],
  "leg-curl-zercher-good-morning-584": ["leg-curl-zercher-good-morning-584/start"],
  "leg-raise-hanging-knee-raise-585": ["leg-raise-hanging-knee-raise-585/start", "leg-raise-hanging-knee-raise-585/end"],
  "leg-raise-lateral-stepover-589": ["leg-raise-lateral-stepover-589/start"],
  "leg-raise-leg-lowering-drill-590": ["leg-raise-leg-lowering-drill-590/start"],
  "leg-raise-medicine-ball-leg-drops-593": ["leg-raise-medicine-ball-leg-drops-593/start"],
  "leg-raise-reverse-leg-raise-595": ["leg-raise-reverse-leg-raise-595/start"],
  "lunge-back-foot-elevated-dumbbell-split-squat-611": ["lunge-back-foot-elevated-dumbbell-split-squat-611/start"],
  "lunge-barbell-bulgarian-split-squat-613": ["lunge-barbell-bulgarian-split-squat-613/start"],
  "lunge-barbell-front-split-squat-615": ["lunge-barbell-front-split-squat-615/start"],
  "lunge-barbell-split-squat-619": ["lunge-barbell-split-squat-619/start"],
  "lunge-dumbbell-bulgarian-split-squat-625": ["lunge-dumbbell-bulgarian-split-squat-625/start", "lunge-dumbbell-bulgarian-split-squat-625/end"],
  "lunge-dumbbell-overhead-bulgarian-split-squat-630": ["lunge-dumbbell-overhead-bulgarian-split-squat-630/start"],
  "lunge-elevated-front-foot-barbell-split-squat-635": ["lunge-elevated-front-foot-barbell-split-squat-635/start"],
  "lunge-front-foot-elevated-dumbbell-split-squat-636": ["lunge-front-foot-elevated-dumbbell-split-squat-636/start"],
  "lunge-low-side-to-side-lunge-640": ["lunge-low-side-to-side-lunge-640/start"],
  "lunge-overhead-bulgarian-split-squat-648": ["lunge-overhead-bulgarian-split-squat-648/start"],
  "lunge-overhead-dumbbell-split-squat-651": ["lunge-overhead-dumbbell-split-squat-651/start"],
  "lunge-wide-grip-overhead-barbell-split-squat-698": ["lunge-wide-grip-overhead-barbell-split-squat-698/start"],
  "machine-row": ["machine-row/start", "machine-row/end"],
  "olympic-lift-barbell-hang-power-clean-699": ["olympic-lift-barbell-hang-power-clean-699/start"],
  "olympic-lift-barbell-hang-power-snatch-700": ["olympic-lift-barbell-hang-power-snatch-700/start"],
  "olympic-lift-barbell-hang-pull-701": ["olympic-lift-barbell-hang-pull-701/start"],
  "olympic-lift-barbell-high-pull-703": ["olympic-lift-barbell-high-pull-703/start"],
  "olympic-lift-barbell-power-clean-704": ["olympic-lift-barbell-power-clean-704/start"],
  "olympic-lift-barbell-power-snatch-705": ["olympic-lift-barbell-power-snatch-705/start"],
  "olympic-lift-barbell-split-jerk-707": ["olympic-lift-barbell-split-jerk-707/start"],
  "olympic-lift-dumbbell-hang-pull-713": ["olympic-lift-dumbbell-hang-pull-713/start"],
  "olympic-lift-dumbbell-power-clean-and-jerk-715": ["olympic-lift-dumbbell-power-clean-and-jerk-715/start"],
  "olympic-lift-dumbbell-power-clean-and-push-press-716": ["olympic-lift-dumbbell-power-clean-and-push-press-716/start"],
  "olympic-lift-dumbbell-power-clean-and-strict-press-717": ["olympic-lift-dumbbell-power-clean-and-strict-press-717/start"],
  "olympic-lift-push-jerk-721": ["olympic-lift-push-jerk-721/start"],
  "olympic-lift-split-jerk-725": ["olympic-lift-split-jerk-725/start"],
  "pec-deck": ["pec-deck/start", "pec-deck/end"],
  "plank-45-degree-plank-728": ["plank-45-degree-plank-728/start"],
  "plank-90-degree-static-hold-729": ["plank-90-degree-static-hold-729/start"],
  "plank-bear-crawl-730": ["plank-bear-crawl-730/start", "plank-bear-crawl-730/end"],
  "plank-cross-body-mountain-climber-731": ["plank-cross-body-mountain-climber-731/start"],
  "plank-elbow-plank-pike-jacks-732": ["plank-elbow-plank-pike-jacks-732/start"],
  "plank-elevated-feet-plank-733": ["plank-elevated-feet-plank-733/start"],
  "plank-elevator-abs-734": ["plank-elevator-abs-734/start"],
  "plank-extended-plank-735": ["plank-extended-plank-735/start", "plank-extended-plank-735/end"],
  "plank-full-plank-passe-twist-736": ["plank-full-plank-passe-twist-736/end"],
  "plank-inching-elbow-plank-737": ["plank-inching-elbow-plank-737/end"],
  "plank-kneeling-plank-739": ["plank-kneeling-plank-739/end"],
  "plank-lying-reverse-plank-742": ["plank-lying-reverse-plank-742/start"],
  "plank-medicine-ball-mountain-climber-743": ["plank-medicine-ball-mountain-climber-743/start"],
  "plank-mountain-climber-745": ["plank-mountain-climber-745/start"],
  "plank-mountain-climber-on-sliding-discs-746": ["plank-mountain-climber-on-sliding-discs-746/start"],
  "plank-mountain-climber-with-hands-on-bench-748": ["plank-mountain-climber-with-hands-on-bench-748/start"],
  "plank-plank-750": ["plank-plank-750/end"],
  "plank-plank-jacks-with-feet-on-sliding-discs-751": ["plank-plank-jacks-with-feet-on-sliding-discs-751/start", "plank-plank-jacks-with-feet-on-sliding-discs-751/end"],
  "plank-plank-knee-twist-752": ["plank-plank-knee-twist-752/start", "plank-plank-knee-twist-752/end"],
  "plank-plank-pike-jumps-753": ["plank-plank-pike-jumps-753/start"],
  "plank-plank-pikes-754": ["plank-plank-pikes-754/start", "plank-plank-pikes-754/end"],
  "plank-plank-to-stand-up-755": ["plank-plank-to-stand-up-755/start"],
  "plank-plank-with-arm-raise-756": ["plank-plank-with-arm-raise-756/start"],
  "plank-plank-with-knee-to-elbow-758": ["plank-plank-with-knee-to-elbow-758/start"],
  "plank-plank-with-leg-lift-759": ["plank-plank-with-leg-lift-759/start"],
  "plank-plank-with-oblique-crunch-760": ["plank-plank-with-oblique-crunch-760/start"],
  "plank-ring-plank-sprawls-762": ["plank-ring-plank-sprawls-762/start", "plank-ring-plank-sprawls-762/end"],
  "plank-side-kick-plank-764": ["plank-side-kick-plank-764/start"],
  "plank-spiderman-plank-778": ["plank-spiderman-plank-778/end"],
  "plank-straight-arm-plank-779": ["plank-straight-arm-plank-779/end"],
  "plank-straight-arm-plank-with-shoulder-touch-780": ["plank-straight-arm-plank-with-shoulder-touch-780/start", "plank-straight-arm-plank-with-shoulder-touch-780/end"],
  "plank-three-way-plank-788": ["plank-three-way-plank-788/end"],
  "plank-two-point-plank-791": ["plank-two-point-plank-791/end"],
  "plank-wide-stance-plank-with-diagonal-arm-lift-855": ["plank-wide-stance-plank-with-diagonal-arm-lift-855/start"],
  "plank-wide-stance-plank-with-diagonal-leg-lift-856": ["plank-wide-stance-plank-with-diagonal-leg-lift-856/start"],
  "plank-wide-stance-plank-with-leg-lift-857": ["plank-wide-stance-plank-with-leg-lift-857/start"],
  "plank-wide-stance-plank-with-opposite-arm-and-leg-lift-858": ["plank-wide-stance-plank-with-opposite-arm-and-leg-lift-858/start"],
  "pull-up-chin-up-902": ["pull-up-chin-up-902/start"],
  "pull-up-close-grip-chin-up-903": ["pull-up-close-grip-chin-up-903/start"],
  "pull-up-crossover-chin-up-905": ["pull-up-crossover-chin-up-905/start"],
  "pull-up-jumping-pull-ups-908": ["pull-up-jumping-pull-ups-908/start"],
  "pull-up-kipping-pull-up-909": ["pull-up-kipping-pull-up-909/start"],
  "pull-up-l-pull-up-912": ["pull-up-l-pull-up-912/start"],
  "pull-up-lat-pulldown-913": ["pull-up-lat-pulldown-913/start", "pull-up-lat-pulldown-913/end"],
  "pull-up-mixed-grip-pull-up-915": ["pull-up-mixed-grip-pull-up-915/start"],
  "pull-up-neutral-grip-pull-up-917": ["pull-up-neutral-grip-pull-up-917/start"],
  "pull-up-pull-up-918": ["pull-up-pull-up-918/start", "pull-up-pull-up-918/end"],
  "pull-up-wide-grip-pull-up-942": ["pull-up-wide-grip-pull-up-942/start"],
  "pullover": ["pullover/start"],
  "push-up-biceps-push-up-945": ["push-up-biceps-push-up-945/start"],
  "push-up-close-grip-medicine-ball-push-up-949": ["push-up-close-grip-medicine-ball-push-up-949/start"],
  "push-up-diamond-push-up-952": ["push-up-diamond-push-up-952/start"],
  "push-up-dynamic-push-up-953": ["push-up-dynamic-push-up-953/start"],
  "push-up-explosive-crossover-push-up-954": ["push-up-explosive-crossover-push-up-954/start"],
  "push-up-hindu-push-up-959": ["push-up-hindu-push-up-959/start"],
  "push-up-isometric-explosive-push-up-961": ["push-up-isometric-explosive-push-up-961/start"],
  "push-up-judo-push-up-962": ["push-up-judo-push-up-962/start"],
  "push-up-push-up-971": ["push-up-push-up-971/start"],
  "push-up-ring-push-up-977": ["push-up-ring-push-up-977/start"],
  "push-up-shoulder-push-up-978": ["push-up-shoulder-push-up-978/start"],
  "push-up-stacked-feet-push-up-982": ["push-up-stacked-feet-push-up-982/start"],
  "push-up-staggered-hands-push-up-983": ["push-up-staggered-hands-push-up-983/start"],
  "push-up-t-push-up-987": ["push-up-t-push-up-987/start"],
  "reverse-pec-deck": ["reverse-pec-deck/start", "reverse-pec-deck/end"],
  "row-barbell-row-1034": ["row-barbell-row-1034/start", "row-barbell-row-1034/end"],
  "row-barbell-straight-leg-deadlift-to-row-1035": ["row-barbell-straight-leg-deadlift-to-row-1035/start"],
  "row-elevated-feet-inverted-row-1042": ["row-elevated-feet-inverted-row-1042/start"],
  "row-face-pull-1044": ["row-face-pull-1044/start", "row-face-pull-1044/end"],
  "row-face-pull-with-external-rotation-1045": ["row-face-pull-with-external-rotation-1045/start"],
  "row-inverted-row-1047": ["row-inverted-row-1047/start"],
  "row-seated-cable-row-1059": ["row-seated-cable-row-1059/start", "row-seated-cable-row-1059/end"],
  "run-indoor-indoor-track-run-1088": ["run-indoor-indoor-track-run-1088/end"],
  "run-indoor-treadmill-1089": ["run-indoor-treadmill-1089/end"],
  "run-run-1084": ["run-run-1084/end"],
  "run-sprint-1086": ["run-sprint-1086/end"],
  "run-walk-1087": ["run-walk-1087/end"],
  "seated-leg-curl": ["seated-leg-curl/start", "seated-leg-curl/end"],
  "shoulder-press": ["shoulder-press/start", "shoulder-press/end"],
  "shoulder-press-barbell-front-squat-to-push-press-1112": ["shoulder-press-barbell-front-squat-to-push-press-1112/start"],
  "shoulder-press-floor-inverted-shoulder-press-1121": ["shoulder-press-floor-inverted-shoulder-press-1121/start"],
  "shoulder-press-inverted-shoulder-press-1122": ["shoulder-press-inverted-shoulder-press-1122/start"],
  "shoulder-press-overhead-barbell-press-1125": ["shoulder-press-overhead-barbell-press-1125/start", "shoulder-press-overhead-barbell-press-1125/end"],
  "shoulder-press-overhead-dumbbell-press-1126": ["shoulder-press-overhead-dumbbell-press-1126/start", "shoulder-press-overhead-dumbbell-press-1126/end"],
  "shoulder-press-seated-dumbbell-shoulder-press-1128": ["shoulder-press-seated-dumbbell-shoulder-press-1128/start", "shoulder-press-seated-dumbbell-shoulder-press-1128/end"],
  "shoulder-stability-dumbbell-face-pull-with-external-rotation-1144": ["shoulder-stability-dumbbell-face-pull-with-external-rotation-1144/start"],
  "shrug-scapular-retraction-1187": ["shrug-scapular-retraction-1187/start"],
  "sit-up-butterfly-sit-up-1198": ["sit-up-butterfly-sit-up-1198/start", "sit-up-butterfly-sit-up-1198/end"],
  "sit-up-crossed-arms-sit-up-1200": ["sit-up-crossed-arms-sit-up-1200/start", "sit-up-crossed-arms-sit-up-1200/end"],
  "sit-up-get-up-sit-up-1201": ["sit-up-get-up-sit-up-1201/start", "sit-up-get-up-sit-up-1201/end"],
  "sit-up-ghd-sit-ups-1202": ["sit-up-ghd-sit-ups-1202/start", "sit-up-ghd-sit-ups-1202/end"],
  "sit-up-hovering-sit-up-1203": ["sit-up-hovering-sit-up-1203/start", "sit-up-hovering-sit-up-1203/end"],
  "sit-up-kettlebell-sit-up-1204": ["sit-up-kettlebell-sit-up-1204/start", "sit-up-kettlebell-sit-up-1204/end"],
  "sit-up-negative-sit-up-1209": ["sit-up-negative-sit-up-1209/start", "sit-up-negative-sit-up-1209/end"],
  "sit-up-reverse-curl-up-1212": ["sit-up-reverse-curl-up-1212/start"],
  "sit-up-sit-up-1215": ["sit-up-sit-up-1215/start", "sit-up-sit-up-1215/end"],
  "sit-up-sit-up-turkish-get-up-1216": ["sit-up-sit-up-turkish-get-up-1216/start", "sit-up-sit-up-turkish-get-up-1216/end"],
  "sled-backward-drag-1237": ["sled-backward-drag-1237/end"],
  "sled-forward-drag-1239": ["sled-forward-drag-1239/end"],
  "sled-low-push-1240": ["sled-low-push-1240/start"],
  "sled-push-1241": ["sled-push-1241/start"],
  "smith-machine-squat": ["smith-machine-squat/start", "smith-machine-squat/end"],
  "squat-air-squat-1246": ["squat-air-squat-1246/start"],
  "squat-back-squat-with-body-bar-1248": ["squat-back-squat-with-body-bar-1248/start"],
  "squat-barbell-back-squat-1251": ["squat-barbell-back-squat-1251/start", "squat-barbell-back-squat-1251/end"],
  "squat-barbell-front-squat-1253": ["squat-barbell-front-squat-1253/start", "squat-barbell-front-squat-1253/end"],
  "squat-barbell-hack-squat-1254": ["squat-barbell-hack-squat-1254/start"],
  "squat-barbell-quarter-squat-1257": ["squat-barbell-quarter-squat-1257/start"],
  "squat-barbell-siff-squat-1258": ["squat-barbell-siff-squat-1258/start"],
  "squat-barbell-stepover-1262": ["squat-barbell-stepover-1262/start"],
  "squat-bench-squat-with-rotational-chop-1263": ["squat-bench-squat-with-rotational-chop-1263/start"],
  "squat-body-weight-wall-squat-1264": ["squat-body-weight-wall-squat-1264/start"],
  "squat-braced-squat-1266": ["squat-braced-squat-1266/start"],
  "squat-crossed-arm-barbell-front-squat-1267": ["squat-crossed-arm-barbell-front-squat-1267/start"],
  "squat-crossover-dumbbell-step-up-1268": ["squat-crossover-dumbbell-step-up-1268/start"],
  "squat-dumbbell-front-squat-1269": ["squat-dumbbell-front-squat-1269/start"],
  "squat-dumbbell-split-squat-1271": ["squat-dumbbell-split-squat-1271/start"],
  "squat-dumbbell-squat-1272": ["squat-dumbbell-squat-1272/start"],
  "squat-dumbbell-stepover-1276": ["squat-dumbbell-stepover-1276/start"],
  "squat-figure-four-squats-1279": ["squat-figure-four-squats-1279/start"],
  "squat-goblet-squat-1280": ["squat-goblet-squat-1280/start"],
  "squat-kettlebell-squat-1281": ["squat-kettlebell-squat-1281/start"],
  "squat-leg-press-1285": ["squat-leg-press-1285/start", "squat-leg-press-1285/end"],
  "squat-overhead-dumbbell-squat-1289": ["squat-overhead-dumbbell-squat-1289/start"],
  "squat-overhead-squat-1290": ["squat-overhead-squat-1290/start"],
  "squat-pistol-squat-1292": ["squat-pistol-squat-1292/start"],
  "squat-plie-squat-1294": ["squat-plie-squat-1294/start"],
  "squat-prisoner-squat-1295": ["squat-prisoner-squat-1295/start"],
  "squat-squat-american-swing-1300": ["squat-squat-american-swing-1300/start", "squat-squat-american-swing-1300/end"],
  "squat-suitcase-squats-1306": ["squat-suitcase-squats-1306/start"],
  "squat-sumo-squat-1307": ["squat-sumo-squat-1307/start"],
  "squat-sumo-squat-slide-in-1308": ["squat-sumo-squat-slide-in-1308/start"],
  "squat-sumo-squat-to-high-pull-1309": ["squat-sumo-squat-to-high-pull-1309/start"],
  "squat-sumo-squat-to-stand-1310": ["squat-sumo-squat-to-stand-1310/start"],
  "squat-sumo-squat-with-rotation-1311": ["squat-sumo-squat-with-rotation-1311/start"],
  "squat-uneven-squat-1314": ["squat-uneven-squat-1314/start"],
  "squat-wall-ball-squat-and-press-1317": ["squat-wall-ball-squat-and-press-1317/start"],
  "squat-wide-stance-goblet-squat-1342": ["squat-wide-stance-goblet-squat-1342/start"],
  "total-body-burpee-1381": ["total-body-burpee-1381/end"],
  "total-body-burpee-box-jump-1382": ["total-body-burpee-box-jump-1382/start"],
  "triceps-extension-bench-dip-1399": ["triceps-extension-bench-dip-1399/start"],
  "triceps-extension-body-weight-dip-1400": ["triceps-extension-body-weight-dip-1400/start"],
  "triceps-extension-cable-kickback-1401": ["triceps-extension-cable-kickback-1401/start"],
  "triceps-extension-cable-lying-triceps-extension-1402": ["triceps-extension-cable-lying-triceps-extension-1402/start"],
  "triceps-extension-cable-overhead-triceps-extension-1403": ["triceps-extension-cable-overhead-triceps-extension-1403/start", "triceps-extension-cable-overhead-triceps-extension-1403/end"],
  "triceps-extension-dumbbell-kickback-1404": ["triceps-extension-dumbbell-kickback-1404/start"],
  "triceps-extension-dumbbell-lying-triceps-extension-1405": ["triceps-extension-dumbbell-lying-triceps-extension-1405/start"],
  "triceps-extension-ez-bar-overhead-triceps-extension-1406": ["triceps-extension-ez-bar-overhead-triceps-extension-1406/start"],
  "triceps-extension-incline-ez-bar-lying-triceps-extension-1408": ["triceps-extension-incline-ez-bar-lying-triceps-extension-1408/start"],
  "triceps-extension-lying-ez-bar-triceps-extension-1410": ["triceps-extension-lying-ez-bar-triceps-extension-1410/start"],
  "triceps-extension-lying-triceps-extension-to-close-grip-bench-press-1411": ["triceps-extension-lying-triceps-extension-to-close-grip-bench-press-1411/start"],
  "triceps-extension-overhead-dumbbell-triceps-extension-1412": ["triceps-extension-overhead-dumbbell-triceps-extension-1412/start"],
  "triceps-extension-reverse-grip-triceps-pressdown-1415": ["triceps-extension-reverse-grip-triceps-pressdown-1415/start"],
  "triceps-extension-rope-pressdown-1416": ["triceps-extension-rope-pressdown-1416/start"],
  "triceps-extension-seated-barbell-overhead-triceps-extension-1417": ["triceps-extension-seated-barbell-overhead-triceps-extension-1417/start"],
  "triceps-extension-seated-dumbbell-overhead-triceps-extension-1418": ["triceps-extension-seated-dumbbell-overhead-triceps-extension-1418/start"],
  "triceps-extension-seated-ez-bar-overhead-triceps-extension-1419": ["triceps-extension-seated-ez-bar-overhead-triceps-extension-1419/start"],
  "triceps-extension-single-dumbbell-seated-overhead-triceps-extension-1422": ["triceps-extension-single-dumbbell-seated-overhead-triceps-extension-1422/start"],
  "triceps-extension-static-lying-triceps-extension-1425": ["triceps-extension-static-lying-triceps-extension-1425/start"],
  "triceps-extension-triceps-extension-on-floor-1431": ["triceps-extension-triceps-extension-on-floor-1431/start"],
  "triceps-extension-triceps-pressdown-1433": ["triceps-extension-triceps-pressdown-1433/start"],
  "warm-up-ankle-circles-1480": ["warm-up-ankle-circles-1480/start"],
  "warm-up-arm-circles-1483": ["warm-up-arm-circles-1483/start"],
  "warm-up-cat-camel-1486": ["warm-up-cat-camel-1486/start"],
  "warm-up-inverted-hamstring-stretch-1491": ["warm-up-inverted-hamstring-stretch-1491/start"],
  "warm-up-lateral-duck-under-1492": ["warm-up-lateral-duck-under-1492/start"],
  "warm-up-neck-rotations-1478": ["warm-up-neck-rotations-1478/start"],
  "warm-up-opposite-arm-and-leg-balance-1494": ["warm-up-opposite-arm-and-leg-balance-1494/start", "warm-up-opposite-arm-and-leg-balance-1494/end"],
  "warm-up-quadruped-rocking-1495": ["warm-up-quadruped-rocking-1495/start"],
  "warm-up-shoulder-circles-1497": ["warm-up-shoulder-circles-1497/start"],
  "warm-up-walking-high-kicks-1505": ["warm-up-walking-high-kicks-1505/start"],
  "warm-up-walking-high-knees-1506": ["warm-up-walking-high-knees-1506/start", "warm-up-walking-high-knees-1506/end"],
  "warm-up-walking-knee-hugs-1507": ["warm-up-walking-knee-hugs-1507/start"],
  "warm-up-walking-leg-cradles-1508": ["warm-up-walking-leg-cradles-1508/start"],
  "warm-up-walkout-from-push-up-position-1510": ["warm-up-walkout-from-push-up-position-1510/start"]
};

export function getExerciseImageAssetKeys(exerciseId: string): ExerciseImageAssetKey[] {
  return exerciseImageAssetKeysById[resolveExerciseId(exerciseId)] ?? [];
}
