import { resolveExerciseId } from "./exercises";

export type ExerciseImageAssetKey = string;

const exerciseImageAssetKeysById: Record<string, ExerciseImageAssetKey[]> = {
  "assisted-pull-up-machine": ["assisted-pull-up-machine/start", "assisted-pull-up-machine/end"],
  "banded-exercises-ab-twist-1": ["banded-exercises-ab-twist-1/start", "banded-exercises-ab-twist-1/end"],
  "banded-exercises-back-extension-2": ["banded-exercises-back-extension-2/start", "banded-exercises-back-extension-2/end"],
  "banded-exercises-bicycle-crunch-3": ["banded-exercises-bicycle-crunch-3/start", "banded-exercises-bicycle-crunch-3/end"],
  "banded-exercises-calf-raises-4": ["banded-exercises-calf-raises-4/start", "banded-exercises-calf-raises-4/end"],
  "banded-exercises-clam-shells-5": ["banded-exercises-clam-shells-5/start", "banded-exercises-clam-shells-5/end"],
  "banded-exercises-curl-6": ["banded-exercises-curl-6/start", "banded-exercises-curl-6/end"],
  "banded-exercises-deadbug-7": ["banded-exercises-deadbug-7/start", "banded-exercises-deadbug-7/end"],
  "bench-press-barbell-bench-press-76": ["bench-press-barbell-bench-press-76/start", "bench-press-barbell-bench-press-76/end"],
  "bench-press-barbell-floor-press-78": ["bench-press-barbell-floor-press-78/start", "bench-press-barbell-floor-press-78/end"],
  "bench-press-close-grip-barbell-bench-press-80": ["bench-press-close-grip-barbell-bench-press-80/start", "bench-press-close-grip-barbell-bench-press-80/end"],
  "bench-press-decline-dumbbell-bench-press-81": ["bench-press-decline-dumbbell-bench-press-81/start", "bench-press-decline-dumbbell-bench-press-81/end"],
  "bench-press-dumbbell-bench-press-82": ["bench-press-dumbbell-bench-press-82/start", "bench-press-dumbbell-bench-press-82/end"],
  "bench-press-dumbbell-floor-press-83": ["bench-press-dumbbell-floor-press-83/start", "bench-press-dumbbell-floor-press-83/end"],
  "bench-press-incline-barbell-bench-press-84": ["bench-press-incline-barbell-bench-press-84/start", "bench-press-incline-barbell-bench-press-84/end"],
  "bench-press-incline-dumbbell-bench-press-85": ["bench-press-incline-dumbbell-bench-press-85/start", "bench-press-incline-dumbbell-bench-press-85/end"],
  "bench-press-incline-smith-machine-bench-press-86": ["bench-press-incline-smith-machine-bench-press-86/start", "bench-press-incline-smith-machine-bench-press-86/end"],
  "bench-press-kettlebell-chest-press-88": ["bench-press-kettlebell-chest-press-88/start", "bench-press-kettlebell-chest-press-88/end"],
  "bench-press-neutral-grip-dumbbell-bench-press-89": ["bench-press-neutral-grip-dumbbell-bench-press-89/start", "bench-press-neutral-grip-dumbbell-bench-press-89/end"],
  "bench-press-neutral-grip-dumbbell-incline-bench-press-90": ["bench-press-neutral-grip-dumbbell-incline-bench-press-90/start", "bench-press-neutral-grip-dumbbell-incline-bench-press-90/end"],
  "bench-press-one-arm-floor-press-91": ["bench-press-one-arm-floor-press-91/start", "bench-press-one-arm-floor-press-91/end"],
  "bench-press-reverse-grip-barbell-bench-press-93": ["bench-press-reverse-grip-barbell-bench-press-93/start", "bench-press-reverse-grip-barbell-bench-press-93/end"],
  "bench-press-reverse-grip-incline-bench-press-94": ["bench-press-reverse-grip-incline-bench-press-94/start", "bench-press-reverse-grip-incline-bench-press-94/end"],
  "bench-press-single-arm-cable-chest-press-95": ["bench-press-single-arm-cable-chest-press-95/start", "bench-press-single-arm-cable-chest-press-95/end"],
  "bench-press-single-arm-dumbbell-bench-press-96": ["bench-press-single-arm-dumbbell-bench-press-96/start", "bench-press-single-arm-dumbbell-bench-press-96/end"],
  "bench-press-smith-machine-bench-press-97": ["bench-press-smith-machine-bench-press-97/start", "bench-press-smith-machine-bench-press-97/end"],
  "bench-press-swiss-ball-dumbbell-chest-press-98": ["bench-press-swiss-ball-dumbbell-chest-press-98/start", "bench-press-swiss-ball-dumbbell-chest-press-98/end"],
  "cable-glute-kickback": ["cable-glute-kickback/start", "cable-glute-kickback/end"],
  "chest-supported-machine-row": ["chest-supported-machine-row/start", "chest-supported-machine-row/end"],
  "curl-alternating-dumbbell-biceps-curl-323": ["curl-alternating-dumbbell-biceps-curl-323/start", "curl-alternating-dumbbell-biceps-curl-323/end"],
  "curl-alternating-dumbbell-biceps-curl-on-swiss-ball-324": ["curl-alternating-dumbbell-biceps-curl-on-swiss-ball-324/start", "curl-alternating-dumbbell-biceps-curl-on-swiss-ball-324/end"],
  "curl-alternating-incline-dumbbell-biceps-curl-325": ["curl-alternating-incline-dumbbell-biceps-curl-325/start", "curl-alternating-incline-dumbbell-biceps-curl-325/end"],
  "curl-barbell-biceps-curl-326": ["curl-barbell-biceps-curl-326/start", "curl-barbell-biceps-curl-326/end"],
  "machine-chest-press": ["machine-chest-press/start", "machine-chest-press/end"],
  "machine-hack-squat": ["machine-hack-squat/start", "machine-hack-squat/end"],
  "machine-hip-abduction": ["machine-hip-abduction/start", "machine-hip-abduction/end"],
  "machine-hip-adduction": ["machine-hip-adduction/start", "machine-hip-adduction/end"],
  "machine-hip-thrust": ["machine-hip-thrust/start", "machine-hip-thrust/end"],
  "machine-row": ["machine-row/start", "machine-row/end"],
  "machine-shoulder-press": ["machine-shoulder-press/start", "machine-shoulder-press/end"],
  "pec-deck": ["pec-deck/start", "pec-deck/end"],
  "rear-delt-machine": ["rear-delt-machine/start", "rear-delt-machine/end"],
  "seated-leg-curl": ["seated-leg-curl/start", "seated-leg-curl/end"],
  "smith-machine-squat": ["smith-machine-squat/start", "smith-machine-squat/end"],
  "deadlift-barbell-deadlift-371": ["deadlift-barbell-deadlift-371/start", "deadlift-barbell-deadlift-371/end"],
  "deadlift-romanian-deadlift-374": ["deadlift-romanian-deadlift-374/start", "deadlift-romanian-deadlift-374/end"],
  "pull-up-lat-pulldown-913": ["pull-up-lat-pulldown-913/start", "pull-up-lat-pulldown-913/end"],
  "pull-up-pull-up-918": ["pull-up-pull-up-918/start", "pull-up-pull-up-918/end"],
  "row-barbell-row-1034": ["row-barbell-row-1034/start", "row-barbell-row-1034/end"],
  "row-seated-cable-row-1059": ["row-seated-cable-row-1059/start", "row-seated-cable-row-1059/end"],
  "row-single-arm-neutral-grip-dumbbell-row-1065": ["row-single-arm-neutral-grip-dumbbell-row-1065/start", "row-single-arm-neutral-grip-dumbbell-row-1065/end"],
  "shoulder-press-overhead-barbell-press-1125": ["shoulder-press-overhead-barbell-press-1125/start", "shoulder-press-overhead-barbell-press-1125/end"],
  "shoulder-press-overhead-dumbbell-press-1126": ["shoulder-press-overhead-dumbbell-press-1126/start", "shoulder-press-overhead-dumbbell-press-1126/end"],
  "squat-barbell-back-squat-1251": ["squat-barbell-back-squat-1251/start", "squat-barbell-back-squat-1251/end"]
};

export function getExerciseImageAssetKeys(exerciseId: string): ExerciseImageAssetKey[] {
  return exerciseImageAssetKeysById[resolveExerciseId(exerciseId)] ?? [];
}
