import type { StageType } from "./workouts";

export const garminCategoryValues = [
  "BANDED_EXERCISES",
  "BATTLE_ROPE",
  "BENCH_PRESS",
  "BIKE_OUTDOOR",
  "CALF_RAISE",
  "CARDIO",
  "CARRY",
  "CHOP",
  "CORE",
  "CRUNCH",
  "CURL",
  "DEADLIFT",
  "DORSIFLEXION",
  "ELLIPTICAL",
  "FLOOR_CLIMB",
  "FLYE",
  "HIP_RAISE",
  "HIP_STABILITY",
  "HIP_SWING",
  "HYPEREXTENSION",
  "INDOOR_BIKE",
  "LADDER",
  "LATERAL_RAISE",
  "LEG_CURL",
  "LEG_EXTENSION",
  "LEG_RAISE",
  "LUNGE",
  "OLYMPIC_LIFT",
  "PLANK",
  "PLYO",
  "PULL_UP",
  "PULLOVER",
  "PUSH_UP",
  "ROW",
  "RUN",
  "RUN_INDOOR",
  "SANDBAG",
  "SHOULDER_PRESS",
  "SHOULDER_STABILITY",
  "SHRUG",
  "SIT_UP",
  "SLED",
  "SLEDGE_HAMMER",
  "SQUAT",
  "STAIR_STEPPER",
  "SUSPENSION",
  "TIRE",
  "TOTAL_BODY",
  "TRICEPS_EXTENSION",
  "WARM_UP"
] as const;

export type GarminCategory = (typeof garminCategoryValues)[number];

export const stageExerciseCategories: Record<StageType, readonly GarminCategory[]> = {
  warmup: [
    "WARM_UP",
    "CARDIO",
    "RUN",
    "RUN_INDOOR",
    "BIKE_OUTDOOR",
    "INDOOR_BIKE",
    "ELLIPTICAL",
    "STAIR_STEPPER",
    "FLOOR_CLIMB",
    "LADDER",
    "HIP_STABILITY",
    "SHOULDER_STABILITY"
  ],
  exercise: [
    "BANDED_EXERCISES",
    "BATTLE_ROPE",
    "BENCH_PRESS",
    "CALF_RAISE",
    "CARRY",
    "CHOP",
    "CORE",
    "CRUNCH",
    "CURL",
    "DEADLIFT",
    "DORSIFLEXION",
    "FLYE",
    "HIP_RAISE",
    "HIP_STABILITY",
    "HIP_SWING",
    "HYPEREXTENSION",
    "LATERAL_RAISE",
    "LEG_CURL",
    "LEG_EXTENSION",
    "LEG_RAISE",
    "LUNGE",
    "OLYMPIC_LIFT",
    "PLANK",
    "PLYO",
    "PULL_UP",
    "PULLOVER",
    "PUSH_UP",
    "ROW",
    "SANDBAG",
    "SHOULDER_PRESS",
    "SHOULDER_STABILITY",
    "SHRUG",
    "SIT_UP",
    "SLED",
    "SLEDGE_HAMMER",
    "SQUAT",
    "SUSPENSION",
    "TIRE",
    "TOTAL_BODY",
    "TRICEPS_EXTENSION"
  ],
  recovery: [
    "WARM_UP",
    "CARDIO",
    "RUN",
    "RUN_INDOOR",
    "BIKE_OUTDOOR",
    "INDOOR_BIKE",
    "ELLIPTICAL",
    "STAIR_STEPPER",
    "HIP_STABILITY",
    "SHOULDER_STABILITY"
  ],
  rest: [],
  cooldown: [
    "WARM_UP",
    "CARDIO",
    "RUN",
    "RUN_INDOOR",
    "BIKE_OUTDOOR",
    "INDOOR_BIKE",
    "ELLIPTICAL",
    "STAIR_STEPPER",
    "HIP_STABILITY",
    "SHOULDER_STABILITY"
  ],
  other: garminCategoryValues
};
