plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.gymmin.fileexport'
version = '1.0.0'

android {
  namespace "com.gymmin.fileexport"

  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  implementation 'androidx.core:core:1.17.0'
}
