import type { Exercise } from "../exercises";

export const calfRaise = [
  {
    "id": "calf-raise-3-way-calf-raise-103",
    "name": "3-way Calf Raise",
    "polishName": "Wznosy łydek — trójpozycyjne",
    "garminCategory": "CALF_RAISE",
    "garminName": "_3_WAY_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-3-way-single-leg-calf-raise-104",
    "name": "3-way Single-leg Calf Raise",
    "polishName": "Wznosy łydki — trójpozycyjne",
    "garminCategory": "CALF_RAISE",
    "garminName": "_3_WAY_SINGLE_LEG_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-3-way-weighted-calf-raise-105",
    "name": "3-way Weighted Calf Raise",
    "polishName": "Wznosy łydek — trójpozycyjne (z obciążeniem)",
    "garminCategory": "CALF_RAISE",
    "garminName": "_3_WAY_WEIGHTED_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-3-way-weighted-single-leg-calf-raise-106",
    "name": "3-way Weighted Single-leg Calf Raise",
    "polishName": "Wznosy łydki — trójpozycyjne (z obciążeniem)",
    "garminCategory": "CALF_RAISE",
    "garminName": "_3_WAY_WEIGHTED_SINGLE_LEG_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-donkey-calf-raise-108",
    "name": "Donkey Calf Raise",
    "polishName": "Wznosy łydek — osiołek",
    "garminCategory": "CALF_RAISE",
    "garminName": "DONKEY_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-seated-calf-raise-109",
    "name": "Seated Calf Raise",
    "polishName": "Wznosy łydek siedząc",
    "garminCategory": "CALF_RAISE",
    "garminName": "SEATED_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-single-leg-bent-knee-calf-raise-111",
    "name": "Single-leg Bent-knee Calf Raise",
    "polishName": "Wznosy łydki przy ugiętym kolanie",
    "garminCategory": "CALF_RAISE",
    "garminName": "SINGLE_LEG_BENT_KNEE_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-single-leg-donkey-calf-raise-113",
    "name": "Single-leg Donkey Calf Raise",
    "polishName": "Wznosy łydki — osiołek",
    "garminCategory": "CALF_RAISE",
    "garminName": "SINGLE_LEG_DONKEY_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-single-leg-standing-calf-raise-115",
    "name": "Single-leg Standing Calf Raise",
    "polishName": "Wznosy łydki stojąc",
    "garminCategory": "CALF_RAISE",
    "garminName": "SINGLE_LEG_STANDING_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-single-leg-standing-dumbbell-calf-raise-116",
    "name": "Single-leg Standing Dumbbell Calf Raise",
    "polishName": "Wznosy łydki z hantlem stojąc",
    "garminCategory": "CALF_RAISE",
    "garminName": "SINGLE_LEG_STANDING_DUMBBELL_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-standing-barbell-calf-raise-117",
    "name": "Standing Barbell Calf Raise",
    "polishName": "Wznosy łydek ze sztangą stojąc",
    "garminCategory": "CALF_RAISE",
    "garminName": "STANDING_BARBELL_CALF_RAISE",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/CALF_RAISE/STANDING_BARBELL_CALF_RAISE",
    "difficulty": "Beginner",
    "description": "The standing barbell calf raise develops size and strength in the lower leg. Use of a weighted barbell creates increased resistance, resulting in targeted development of the calf muscles.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-standing-calf-raise-118",
    "name": "Standing Calf Raise",
    "polishName": "Wspięcia na palce stojąc",
    "garminCategory": "CALF_RAISE",
    "garminName": "STANDING_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "calf-raise-standing-dumbbell-calf-raise-119",
    "name": "Standing Dumbbell Calf Raise",
    "polishName": "Wznosy łydek z hantlem stojąc",
    "garminCategory": "CALF_RAISE",
    "garminName": "STANDING_DUMBBELL_CALF_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  }
] satisfies readonly Exercise[];
