import type { Exercise } from "../exercises";

export const cardio = [
  {
    "id": "cardio-bob-and-weave-circle-125",
    "name": "Bob and Weave Circle",
    "polishName": "Krążenie tułowiem z unikiem",
    "garminCategory": "CARDIO",
    "garminName": "BOB_AND_WEAVE_CIRCLE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-cardio-core-crawl-126",
    "name": "Cardio Core Crawl",
    "polishName": "Chód niedźwiedzia — kardio",
    "garminCategory": "CARDIO",
    "garminName": "CARDIO_CORE_CRAWL",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/CARDIO/CARDIO_CORE_CRAWL",
    "difficulty": "Beginner",
    "description": "The cardio core crawl is a dynamic, multi-joint exercise that targets the core, hips, and glutes. The exercise also strengthens the lower back and shoulders.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 0,
      "hips": 1,
      "lats": 0,
      "lowerBack": 2,
      "obliques": 0,
      "quads": 2,
      "shoulders": 2,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-double-under-127",
    "name": "Double Under",
    "polishName": "Podwójne obrócenie skakanki w jednym skoku",
    "garminCategory": "CARDIO",
    "garminName": "DOUBLE_UNDER",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 1,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-jump-rope-128",
    "name": "Jump Rope",
    "polishName": "Skakanie na skakance",
    "garminCategory": "CARDIO",
    "garminName": "JUMP_ROPE",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/CARDIO/JUMP_ROPE",
    "difficulty": "Intermediate",
    "description": "Jumping rope is a full body conditioning drill that develops foot work, speed and agility. This exercise also improves cardiovascular endurance and coordination.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 1,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-jump-rope-crossover-129",
    "name": "Jump Rope Crossover",
    "polishName": "Skakanie na skakance z krzyżowaniem rąk",
    "garminCategory": "CARDIO",
    "garminName": "JUMP_ROPE_CROSSOVER",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 1,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-jump-rope-jog-130",
    "name": "Jump Rope Jog",
    "polishName": "Skakanie na skakance z naprzemiennym unoszeniem kolan",
    "garminCategory": "CARDIO",
    "garminName": "JUMP_ROPE_JOG",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 1,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-jumping-jacks-131",
    "name": "Jumping Jacks",
    "polishName": "Pajacyki",
    "garminCategory": "CARDIO",
    "garminName": "JUMPING_JACKS",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/CARDIO/JUMPING_JACKS",
    "difficulty": "Beginner",
    "description": "This dynamic full-body exercise is a popular warm-up that increases body temperature, aerobic capacity, and strength.",
    "muscleImpact": {
      "abductors": 1,
      "abs": 0,
      "adductors": 1,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 1,
      "shoulders": 2,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-ski-moguls-132",
    "name": "Ski Moguls",
    "polishName": "Ski Moguls",
    "garminCategory": "CARDIO",
    "garminName": "SKI_MOGULS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-split-jacks-133",
    "name": "Split Jacks",
    "polishName": "Półpajacyki",
    "garminCategory": "CARDIO",
    "garminName": "SPLIT_JACKS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 1,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-squat-jacks-134",
    "name": "Squat Jacks",
    "polishName": "Przysiady rozkroczne z wyskokiem",
    "garminCategory": "CARDIO",
    "garminName": "SQUAT_JACKS",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/CARDIO/SQUAT_JACKS",
    "difficulty": "Intermediate",
    "description": "Squat jacks are a lower-body power and strength exercise that target the quads, glutes, and hamstrings. The exercise also improves hip mobility and cardiovascular endurance.",
    "muscleImpact": {
      "abductors": 2,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-triple-under-135",
    "name": "Triple Under",
    "polishName": "Potrójne obrócenie skakanki w jednym skoku",
    "garminCategory": "CARDIO",
    "garminName": "TRIPLE_UNDER",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 1,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    }
  },
  {
    "id": "cardio-weighted-bob-and-weave-circle-136",
    "name": "Weighted Bob and Weave Circle",
    "polishName": "Krążenie tułowiem z unikiem (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_BOB_AND_WEAVE_CIRCLE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  },
  {
    "id": "cardio-weighted-cardio-core-crawl-137",
    "name": "Weighted Cardio Core Crawl",
    "polishName": "Chód niedźwiedzia — kardio (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_CARDIO_CORE_CRAWL",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 0,
      "hips": 1,
      "lats": 0,
      "lowerBack": 2,
      "obliques": 0,
      "quads": 2,
      "shoulders": 2,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  },
  {
    "id": "cardio-weighted-double-under-138",
    "name": "Weighted Double Under",
    "polishName": "Podwójne obrócenie skakanki w jednym skoku (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_DOUBLE_UNDER",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 1,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  },
  {
    "id": "cardio-weighted-jump-rope-139",
    "name": "Weighted Jump Rope",
    "polishName": "Skakanie na skakance (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_JUMP_ROPE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 1,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  },
  {
    "id": "cardio-weighted-jump-rope-crossover-140",
    "name": "Weighted Jump Rope Crossover",
    "polishName": "Skakanie na skakance z krzyżowaniem rąk (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_JUMP_ROPE_CROSSOVER",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 1,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  },
  {
    "id": "cardio-weighted-jump-rope-jog-141",
    "name": "Weighted Jump Rope Jog",
    "polishName": "Skakanie na skakance z naprzemiennym unoszeniem kolan (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_JUMP_ROPE_JOG",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 1,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  },
  {
    "id": "cardio-weighted-jumping-jacks-142",
    "name": "Weighted Jumping Jacks",
    "polishName": "Pajacyki (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_JUMPING_JACKS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 1,
      "abs": 0,
      "adductors": 1,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 1,
      "shoulders": 2,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  },
  {
    "id": "cardio-weighted-ski-moguls-143",
    "name": "Weighted Ski Moguls",
    "polishName": "Jazda po muldach na półpiłce Bosu® (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_SKI_MOGULS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  },
  {
    "id": "cardio-weighted-split-jacks-144",
    "name": "Weighted Split Jacks",
    "polishName": "Półpajacyki (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_SPLIT_JACKS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 1,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  },
  {
    "id": "cardio-weighted-squat-jacks-145",
    "name": "Weighted Squat Jacks",
    "polishName": "Przysiady rozkroczne z wyskokiem (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_SQUAT_JACKS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 2,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  },
  {
    "id": "cardio-weighted-triple-under-146",
    "name": "Weighted Triple Under",
    "polishName": "Potrójne obrócenie skakanki w jednym skoku (z obciążeniem)",
    "garminCategory": "CARDIO",
    "garminName": "WEIGHTED_TRIPLE_UNDER",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 1,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 1,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 1
    }
  }
] satisfies readonly Exercise[];
