import type { Exercise } from "../exercises";

export const carry = [
  {
    "id": "carry-bar-holds-147",
    "name": "Bar Holds",
    "polishName": "Trzymanie drążka",
    "category": "CARRY",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 3,
      "quads": 0,
      "shoulders": 2,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "carry-dumbbell-waiter-carry-149",
    "name": "Dumbbell Waiter Carry",
    "polishName": "Spacer kelnera z hantlem",
    "category": "CARRY",
    "muscleImpact": {
      "abductors": 0,
      "abs": 5,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 4,
      "glutes": 2,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 4,
      "quads": 2,
      "shoulders": 5,
      "traps": 4,
      "triceps": 3
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "carry-farmers-carry-walk-lunge-152",
    "name": "Farmer's Carry Walk Lunge",
    "polishName": "Wykroki z noszeniem ciężarów",
    "category": "CARRY",
    "muscleImpact": {
      "abductors": 2,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 5,
      "glutes": 4,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 3,
      "quads": 5,
      "shoulders": 2,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "carry-farmers-walk-153",
    "name": "Farmer's Walk",
    "polishName": "Spacer farmera",
    "category": "CARRY",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 5,
      "glutes": 2,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 3,
      "quads": 2,
      "shoulders": 2,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "carry-farmers-walk-on-toes-154",
    "name": "Farmer's Walk on Toes",
    "polishName": "Spacer farmera na palcach",
    "category": "CARRY",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 5,
      "chest": 0,
      "forearm": 5,
      "glutes": 2,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 3,
      "quads": 2,
      "shoulders": 2,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "carry-hex-dumbbell-hold-155",
    "name": "Hex Dumbbell Hold",
    "polishName": "Trzymanie hantla sześciokątnego",
    "category": "CARRY",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 3,
      "quads": 0,
      "shoulders": 2,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "carry-overhead-carry-156",
    "name": "Overhead Carry",
    "polishName": "Chód z ciężarem nad głową",
    "category": "CARRY",
    "muscleImpact": {
      "abductors": 0,
      "abs": 5,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 4,
      "glutes": 2,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 4,
      "quads": 2,
      "shoulders": 5,
      "traps": 4,
      "triceps": 3
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  }
] satisfies readonly Exercise[];
