import type { Exercise } from "../exercises";

export const curl = [
  {
    "id": "curl-alternating-dumbbell-biceps-curl-323",
    "name": "Alternating Dumbbell Biceps Curl",
    "polishName": "Naprzemienne uginanie ramion z hantlami",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-alternating-dumbbell-biceps-curl-on-swiss-ball-324",
    "name": "Alternating Dumbbell Biceps Curl on Swiss Ball",
    "polishName": "Naprzemienne uginanie ramion z hantlami na piłce gimnastycznej",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-alternating-incline-dumbbell-biceps-curl-325",
    "name": "Alternating Incline Dumbbell Biceps Curl",
    "polishName": "Naprzemienne uginanie ramion z hantlami na ławce dodatniej",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-barbell-biceps-curl-326",
    "name": "Barbell Biceps Curl",
    "polishName": "Uginanie ramion ze sztangą",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-barbell-reverse-wrist-curl-327",
    "name": "Barbell Reverse Wrist Curl",
    "polishName": "Odwrócone uginanie nadgarstków ze sztangą",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 1,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-barbell-wrist-curl-328",
    "name": "Barbell Wrist Curl",
    "polishName": "Uginanie nadgarstków ze sztangą",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 1,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-behind-the-back-barbell-reverse-wrist-curl-329",
    "name": "Behind-the-Back Barbell Reverse Wrist Curl",
    "polishName": "Odwrócone uginanie nadgarstków ze sztangą za plecami",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 1,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-behind-the-back-one-arm-cable-curl-330",
    "name": "Behind-the-Back One-arm Cable Curl",
    "polishName": "Uginanie ramienia zza pleców z linką wyciągu dolnego",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-cable-biceps-curl-331",
    "name": "Cable Biceps Curl",
    "polishName": "Uginanie ramion na wyciągu",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-cable-hammer-curl-332",
    "name": "Cable Hammer Curl",
    "polishName": "Uginanie ramion w chwycie młotkowym",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 4,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-cheating-barbell-biceps-curl-333",
    "name": "Cheating Barbell Biceps Curl",
    "polishName": "Uginanie ramion ze sztangą (z większym obciążeniem)",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 2,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-close-grip-ez-bar-biceps-curl-334",
    "name": "Close-grip EZ-Bar Biceps Curl",
    "polishName": "Uginanie ramion ze sztangą łamaną w chwycie wąskim",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-cross-body-dumbbell-hammer-curl-335",
    "name": "Cross-body Dumbbell Hammer Curl",
    "polishName": "Uginanie ramienia z hantlem w chwycie młotkowym w poprzek ciała",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 4,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-dead-hang-biceps-curl-337",
    "name": "Dead-hang Biceps Curl",
    "polishName": "Uginanie ramion ze swobodnego zwisu",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-decline-hammer-curl-338",
    "name": "Decline Hammer Curl",
    "polishName": "Uginanie ramion z hantlami w chwycie młotkowym na ławce ujemnej",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 4,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-dumbbell-biceps-curl-339",
    "name": "Dumbbell Biceps Curl",
    "polishName": "Uginanie ramion z hantlami",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-dumbbell-biceps-curl-with-static-hold-340",
    "name": "Dumbbell Biceps Curl with Static Hold",
    "polishName": "Uginanie ramion z hantlami z przytrzymaniem",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-dumbbell-hammer-curl-341",
    "name": "Dumbbell Hammer Curl",
    "polishName": "Uginanie ramion z hantlami w chwycie młotkowym",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 4,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-dumbbell-reverse-wrist-curl-342",
    "name": "Dumbbell Reverse Wrist Curl",
    "polishName": "Odwrócone uginanie nadgarstków z hantlami",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 1,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-dumbbell-wrist-curl-343",
    "name": "Dumbbell Wrist Curl",
    "polishName": "Uginanie nadgarstków z hantlami",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 1,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-ez-bar-preacher-curl-344",
    "name": "EZ-Bar Preacher Curl",
    "polishName": "Uginanie ramion ze sztangą łamaną na modlitewniku",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-forward-bend-biceps-curl-345",
    "name": "Forward Bend Biceps Curl",
    "polishName": "Uginanie ramion w skłonie w przód",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-hammer-curl-to-press-346",
    "name": "Hammer Curl to Press",
    "polishName": "Uginanie ramion z hantlami w chwycie młotkowym z wyciskaniem",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 4,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 5,
      "traps": 2,
      "triceps": 4
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-incline-dumbbell-biceps-curl-347",
    "name": "Incline Dumbbell Biceps Curl",
    "polishName": "Uginanie ramion z hantlami na ławce dodatniej",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-kettlebell-biceps-curl-349",
    "name": "Kettlebell Biceps Curl",
    "polishName": "Uginanie ramion z odważnikiem",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 1,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-lying-concentration-cable-curl-350",
    "name": "Lying Concentration Cable Curl",
    "polishName": "Uginanie ramion z linką wyciągu dolnego leżąc",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-one-arm-concentration-curl-351",
    "name": "One-arm Concentration Curl",
    "polishName": "Uginanie ramienia z hantlem w podporze o kolano",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-one-arm-preacher-curl-352",
    "name": "One-arm Preacher Curl",
    "polishName": "Uginanie ramienia na modlitewniku",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-plate-pinch-curl-353",
    "name": "Plate Pinch Curl",
    "polishName": "Uginanie ramion z talerzami w dłoniach",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 1,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-preacher-curl-with-cable-354",
    "name": "Preacher Curl with Cable",
    "polishName": "Uginanie ramion na modlitewniku z linką wyciągu dolnego",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-reverse-ez-bar-curl-355",
    "name": "Reverse EZ-Bar Curl",
    "polishName": "Uginanie ramion ze sztangą łamaną nachwytem",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-reverse-grip-barbell-biceps-curl-356",
    "name": "Reverse-grip Barbell Biceps Curl",
    "polishName": "Uginanie ramion ze sztangą nachwytem",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-reverse-grip-wrist-curl-357",
    "name": "Reverse-grip Wrist Curl",
    "polishName": "Odwrócone uginanie nadgarstków",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 1,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-seated-alternating-dumbbell-biceps-curl-358",
    "name": "Seated Alternating Dumbbell Biceps Curl",
    "polishName": "Naprzemienne uginanie ramion z hantlami siedząc",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-seated-dumbbell-biceps-curl-359",
    "name": "Seated Dumbbell Biceps Curl",
    "polishName": "Uginanie ramion z hantlami siedząc",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-seated-reverse-dumbbell-curl-360",
    "name": "Seated Reverse Dumbbell Curl",
    "polishName": "Uginanie ramion z hantlami nachwytem siedząc",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-split-stance-offset-pinky-dumbbell-curl-361",
    "name": "Split-stance Offset Pinky Dumbbell Curl",
    "polishName": "Uginanie ramion z hantlami z jedną nogą na ławce płaskiej",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-standing-ez-bar-biceps-curl-364",
    "name": "Standing EZ-Bar Biceps Curl",
    "polishName": "Uginanie ramion ze sztangą łamaną stojąc",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-standing-zottman-biceps-curl-365",
    "name": "Standing Zottman Biceps Curl",
    "polishName": "Uginanie ramion Zottmana stojąc",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 4,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-static-curl-366",
    "name": "Static Curl",
    "polishName": "Uginanie ramion z przytrzymaniem",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-swiss-ball-ez-bar-preacher-curl-368",
    "name": "Swiss Ball EZ-Bar Preacher Curl",
    "polishName": "Uginanie ramion ze sztangą łamaną na piłce gimnastycznej",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-twisting-standing-dumbbell-biceps-curl-369",
    "name": "Twisting Standing Dumbbell Biceps Curl",
    "polishName": "Uginanie ramion z hantlami z rotacją nadgarsków stojąc",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "curl-wide-grip-ez-bar-biceps-curl-370",
    "name": "Wide-grip EZ-Bar Biceps Curl",
    "polishName": "Uginanie ramion ze sztangą łamaną w chwycie szerokim",
    "category": "CURL",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  }
] satisfies readonly Exercise[];
