import type { Exercise } from "../exercises";

export const deadlift = [
  {
    "id": "deadlift-barbell-deadlift-371",
    "name": "Barbell Deadlift",
    "polishName": "Martwy ciąg ze sztangą",
    "garminCategory": "DEADLIFT",
    "garminName": "BARBELL_DEADLIFT",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/DEADLIFT/BARBELL_DEADLIFT",
    "difficulty": "Advanced",
    "description": "The barbell deadlift builds total-body strength by targeting the lower back, hamstrings, quads, and glutes. The exercise also increases core strength and stability.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-barbell-straight-leg-deadlift-372",
    "name": "Barbell Straight-leg Deadlift",
    "polishName": "Martwy ciąg ze sztangą na wyprostowanych nogach",
    "garminCategory": "DEADLIFT",
    "garminName": "BARBELL_STRAIGHT_LEG_DEADLIFT",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/DEADLIFT/BARBELL_STRAIGHT_LEG_DEADLIFT",
    "difficulty": "Intermediate",
    "description": "The barbell straight-leg deadlift builds strength in the core, hamstrings, glutes, and lower back. Correctly performing this exercise depends on mastering the hip hinge, which requires you to push your hips back and feel a stretch in your hamstrings to start the movement. Proper form includes not rounding your upper or lower back and keeping the barbell as close as possible to your body.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-dumbbell-deadlift-375",
    "name": "Dumbbell Deadlift",
    "polishName": "Martwy ciąg z hantlami",
    "garminCategory": "DEADLIFT",
    "garminName": "DUMBBELL_DEADLIFT",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/DEADLIFT/DUMBBELL_DEADLIFT",
    "difficulty": "Intermediate",
    "description": "The dumbbell deadlift is a dynamic multi-joint exercise that builds strength in the lower body as well as the back, shoulders, and core, making it a great total-body exercise. By using dumbbells you're able to achieve a greater range of motion. Starting with dumbbells can also be helpful when you're learning the dumbbell movement as they allow for lower total weight to be used.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-dumbbell-single-leg-deadlift-to-row-376",
    "name": "Dumbbell Single-leg Deadlift to Row",
    "polishName": "Martwy ciąg jednonóż z wiosłowaniem z hantlami",
    "garminCategory": "DEADLIFT",
    "garminName": "DUMBBELL_SINGLE_LEG_DEADLIFT_TO_ROW",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 2,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 1,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 1,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "deadlift-dumbbell-straight-leg-deadlift-377",
    "name": "Dumbbell Straight-leg Deadlift",
    "polishName": "Martwy ciąg z hantlami na wyprostowanych nogach",
    "garminCategory": "DEADLIFT",
    "garminName": "DUMBBELL_STRAIGHT_LEG_DEADLIFT",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/DEADLIFT/DUMBBELL_STRAIGHT_LEG_DEADLIFT",
    "difficulty": "Intermediate",
    "description": "The dumbbell straight-leg deadlift strengthens the lower back, with an emphasis on the hamstrings and glutes. Performing the exercise with dumbbells will improve balance and stability on each side of the body while strengthening the core.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-kettlebell-deadlift-378",
    "name": "Kettlebell Deadlift",
    "polishName": "Martwy ciąg z odważnikiem",
    "garminCategory": "DEADLIFT",
    "garminName": "KETTLEBELL_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 1,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 1,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-kettlebell-sumo-deadlift-380",
    "name": "Kettlebell Sumo Deadlift",
    "polishName": "Martwy ciąg w pozycji sumo z odważnikiem",
    "garminCategory": "DEADLIFT",
    "garminName": "KETTLEBELL_SUMO_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 1,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 1,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hyperextension-medicine-ball-deadlift-to-reach-501",
    "name": "Medicine Ball Deadlift-to-Reach",
    "polishName": "Martwy ciąg z unoszeniem piłki lekarskiej",
    "garminCategory": "DEADLIFT",
    "garminName": "MEDICINE_BALL_DEADLIFT_TO_REACH",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 1,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 1,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 1,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-one-arm-one-leg-deadlift-381",
    "name": "One-arm One-leg Deadlift",
    "polishName": "Martwy ciąg jednorącz i jednonóż",
    "garminCategory": "DEADLIFT",
    "garminName": "ONE_ARM_ONE_LEG_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "deadlift-rack-pull-382",
    "name": "Rack Pull",
    "polishName": "Przyciąganie ciężaru ze stojaka",
    "garminCategory": "DEADLIFT",
    "garminName": "RACK_PULL",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 1,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-romanian-deadlift-374",
    "name": "Romanian Deadlift",
    "polishName": "Rumuński martwy ciąg",
    "garminCategory": "DEADLIFT",
    "garminName": "ROMANIAN_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 1,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 2,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-rotational-dumbbell-straight-leg-deadlift-383",
    "name": "Rotational Dumbbell Straight-leg Deadlift",
    "polishName": "Martwy ciąg jednonóż z rotacją",
    "garminCategory": "DEADLIFT",
    "garminName": "ROTATIONAL_DUMBBELL_STRAIGHT_LEG_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-single-arm-deadlift-384",
    "name": "Single-arm Deadlift",
    "polishName": "Martwy ciąg jednorącz",
    "garminCategory": "DEADLIFT",
    "garminName": "SINGLE_ARM_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "deadlift-single-leg-barbell-deadlift-385",
    "name": "Single-leg Barbell Deadlift",
    "polishName": "Martwy ciąg jednonóż ze sztangą",
    "garminCategory": "DEADLIFT",
    "garminName": "SINGLE_LEG_BARBELL_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "deadlift-single-leg-barbell-straight-leg-deadlift-386",
    "name": "Single-leg Barbell Straight-leg Deadlift",
    "polishName": "Martwy ciąg jednonóż z wyprostowaną nogą ze sztangą",
    "garminCategory": "DEADLIFT",
    "garminName": "SINGLE_LEG_BARBELL_STRAIGHT_LEG_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "deadlift-single-leg-rdl-circuit-388",
    "name": "Single-leg RDL Circuit",
    "polishName": "Trening obwodowy jednonóż z rumuńskim martwym ciągiem",
    "garminCategory": "DEADLIFT",
    "garminName": "SINGLE_LEG_RDL_CIRCUIT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "deprecated"
  },
  {
    "id": "deadlift-single-leg-romanian-deadlift-with-dumbbell-390",
    "name": "Single-leg Romanian Deadlift with Dumbbell",
    "polishName": "Rumuński martwy ciąg jednonóż z hantlami",
    "garminCategory": "DEADLIFT",
    "garminName": "SINGLE_LEG_ROMANIAN_DEADLIFT_WITH_DUMBBELL",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "deadlift-straight-leg-deadlift-395",
    "name": "Straight-leg Deadlift",
    "polishName": "Martwy ciąg na wyprostowanych nogach",
    "garminCategory": "DEADLIFT",
    "garminName": "STRAIGHT_LEG_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-sumo-deadlift-391",
    "name": "Sumo Deadlift",
    "polishName": "Martwy ciąg w pozycji sumo",
    "garminCategory": "DEADLIFT",
    "garminName": "SUMO_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 1,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-sumo-deadlift-high-pull-392",
    "name": "Sumo Deadlift High Pull",
    "polishName": "Martwy ciąg w pozycji sumo z podciąganiem sztangi do brody",
    "garminCategory": "DEADLIFT",
    "garminName": "SUMO_DEADLIFT_HIGH_PULL",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 1,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 0,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 1,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-trap-bar-deadlift-393",
    "name": "Trap-bar Deadlift",
    "polishName": "Martwy ciąg z kratownicą",
    "garminCategory": "DEADLIFT",
    "garminName": "TRAP_BAR_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 1,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-wide-grip-barbell-deadlift-394",
    "name": "Wide-grip Barbell Deadlift",
    "polishName": "Martwy ciąg ze sztangą w chwycie szerokim",
    "garminCategory": "DEADLIFT",
    "garminName": "WIDE_GRIP_BARBELL_DEADLIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 1,
      "hips": 0,
      "lats": 2,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 2,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  }
] satisfies readonly Exercise[];
