import type { Exercise } from "../exercises";

export const deadlift = [
  {
    "id": "deadlift-barbell-deadlift-371",
    "name": "Barbell Deadlift",
    "polishName": "Martwy ciąg ze sztangą",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 3,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-barbell-straight-leg-deadlift-372",
    "name": "Barbell Straight-leg Deadlift",
    "polishName": "Martwy ciąg ze sztangą na wyprostowanych nogach",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-dumbbell-deadlift-375",
    "name": "Dumbbell Deadlift",
    "polishName": "Martwy ciąg z hantlami",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 3,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-dumbbell-straight-leg-deadlift-377",
    "name": "Dumbbell Straight-leg Deadlift",
    "polishName": "Martwy ciąg z hantlami na wyprostowanych nogach",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-kettlebell-deadlift-378",
    "name": "Kettlebell Deadlift",
    "polishName": "Martwy ciąg z odważnikiem",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 3,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 1,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-kettlebell-sumo-deadlift-380",
    "name": "Kettlebell Sumo Deadlift",
    "polishName": "Martwy ciąg w pozycji sumo z odważnikiem",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 5,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 2,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 4,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 1,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hyperextension-medicine-ball-deadlift-to-reach-501",
    "name": "Medicine Ball Deadlift-to-Reach",
    "polishName": "Martwy ciąg z unoszeniem piłki lekarskiej",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 3,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 1,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-rack-pull-382",
    "name": "Rack Pull",
    "polishName": "Przyciąganie ciężaru ze stojaka",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 4,
      "glutes": 4,
      "hamstrings": 3,
      "hips": 0,
      "lats": 3,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 1,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-romanian-deadlift-374",
    "name": "Romanian Deadlift",
    "polishName": "Rumuński martwy ciąg",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-rotational-dumbbell-straight-leg-deadlift-383",
    "name": "Rotational Dumbbell Straight-leg Deadlift",
    "polishName": "Martwy ciąg jednonóż z rotacją",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 4,
      "quads": 1,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-single-arm-deadlift-384",
    "name": "Single-arm Deadlift",
    "polishName": "Martwy ciąg jednorącz",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 3,
      "quads": 3,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "deadlift-straight-leg-deadlift-395",
    "name": "Straight-leg Deadlift",
    "polishName": "Martwy ciąg na wyprostowanych nogach",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-sumo-deadlift-391",
    "name": "Sumo Deadlift",
    "polishName": "Martwy ciąg w pozycji sumo",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 5,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 2,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 4,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-sumo-deadlift-high-pull-392",
    "name": "Sumo Deadlift High Pull",
    "polishName": "Martwy ciąg w pozycji sumo z podciąganiem sztangi do brody",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 5,
      "biceps": 2,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 2,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 4,
      "shoulders": 4,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-trap-bar-deadlift-393",
    "name": "Trap-bar Deadlift",
    "polishName": "Martwy ciąg z kratownicą",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 2,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "deadlift-wide-grip-barbell-deadlift-394",
    "name": "Wide-grip Barbell Deadlift",
    "polishName": "Martwy ciąg ze sztangą w chwycie szerokim",
    "category": "DEADLIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 2,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 3,
      "shoulders": 0,
      "traps": 3,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  }
] satisfies readonly Exercise[];
