import type { Exercise } from "../exercises";

export const hipStability = [
  {
    "id": "hip-stability-band-side-lying-leg-raise-451",
    "name": "Band Side-lying Leg Raise",
    "polishName": "Wznosy wyprostowanej nogi w leżeniu bokiem (z gumą oporową)",
    "garminCategory": "HIP_STABILITY",
    "garminName": "BAND_SIDE_LYING_LEG_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 1,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 1,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-dead-bug-452",
    "name": "Dead Bug",
    "polishName": "Martwy robak",
    "garminCategory": "HIP_STABILITY",
    "garminName": "DEAD_BUG",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 2,
      "hips": 1,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 2,
      "shoulders": 1,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-external-hip-raise-453",
    "name": "External Hip Raise",
    "polishName": "Wznosy biodra na zewnątrz leżąc bokiem",
    "garminCategory": "HIP_STABILITY",
    "garminName": "EXTERNAL_HIP_RAISE",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/HIP_STABILITY/EXTERNAL_HIP_RAISE",
    "difficulty": "Beginner",
    "description": "The external hip raise increases strength and stability in hips and glutes. The exercise also actively engages the core.",
    "muscleImpact": {
      "abductors": 1,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-fire-hydrant-kicks-454",
    "name": "Fire Hydrant Kicks",
    "polishName": "Unoszenie nogi w bok w klęku podpartym",
    "garminCategory": "HIP_STABILITY",
    "garminName": "FIRE_HYDRANT_KICKS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 1,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 1,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-hip-circles-455",
    "name": "Hip Circles",
    "polishName": "Krążenie biodrami",
    "garminCategory": "HIP_STABILITY",
    "garminName": "HIP_CIRCLES",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 2,
      "hips": 1,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 2,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-inner-thigh-lift-457",
    "name": "Inner-thigh Lift",
    "polishName": "Unoszenie nogi w leżeniu bocznym",
    "garminCategory": "HIP_STABILITY",
    "garminName": "INNER_THIGH_LIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 1,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-lateral-walks-with-band-at-ankles-458",
    "name": "Lateral Walks with Band at Ankles",
    "polishName": "Chód bokiem (z gumą oporową na kostkach)",
    "garminCategory": "HIP_STABILITY",
    "garminName": "LATERAL_WALKS_WITH_BAND_AT_ANKLES",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 1,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 1,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "machine-hip-abduction",
    "name": "Machine Hip Abduction",
    "polishName": "Odwodzenie bioder na maszynie",
    "garminCategory": "HIP_STABILITY",
    "garminName": "MACHINE_HIP_ABDUCTION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "Beginner",
    "description": "A popular isolation exercise for the lateral glutes.",
    "muscleImpact": {
      "abductors": 2,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "machine-hip-adduction",
    "name": "Machine Hip Adduction",
    "polishName": "Przywodzenie bioder na maszynie",
    "garminCategory": "HIP_STABILITY",
    "garminName": "MACHINE_HIP_ADDUCTION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "Beginner",
    "description": "A useful isolation exercise for the inner thigh muscles.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-prone-hip-internal-rotation-461",
    "name": "Prone Hip Internal Rotation",
    "polishName": "Rotacja wewnętrzna biodra w leżeniu przodem",
    "garminCategory": "HIP_STABILITY",
    "garminName": "PRONE_HIP_INTERNAL_ROTATION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 1,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-quadruped-462",
    "name": "Quadruped",
    "polishName": "Klęk podparty",
    "garminCategory": "HIP_STABILITY",
    "garminName": "QUADRUPED",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 1,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-quadruped-hip-extension-463",
    "name": "Quadruped Hip Extension",
    "polishName": "Wyprost biodra w klęku podpartym",
    "garminCategory": "HIP_STABILITY",
    "garminName": "QUADRUPED_HIP_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hyperextension-side-step-506",
    "name": "Side Step",
    "polishName": "Krok odstawno-dostawny",
    "garminCategory": "HIP_STABILITY",
    "garminName": "SIDE_STEP",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 2,
      "abs": 0,
      "adductors": 2,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "stage2-side-lying-leg-lift",
    "name": "Side-lying Leg Lift",
    "polishName": "Unoszenie nogi bokiem w leżeniu",
    "garminCategory": "HIP_STABILITY",
    "garminName": "SIDE_LYING_LEG_LIFT",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "Beginner",
    "description": "A side-lying hip-abduction movement for the lateral glutes.",
    "muscleImpact": {
      "abductors": 2,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 0,
      "hips": 1,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-side-lying-leg-raise-465",
    "name": "Side-lying Leg Raise",
    "polishName": "Wznosy wyprostowanej nogi w leżeniu bokiem",
    "garminCategory": "HIP_STABILITY",
    "garminName": "SIDE_LYING_LEG_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 1,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-sliding-hip-adduction-466",
    "name": "Sliding Hip Adduction",
    "polishName": "Przywodzenie bioder na dysku ślizgowym",
    "garminCategory": "HIP_STABILITY",
    "garminName": "SLIDING_HIP_ADDUCTION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 1,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-standing-adduction-467",
    "name": "Standing Adduction",
    "polishName": "Przywodzenie bioder stojąc",
    "garminCategory": "HIP_STABILITY",
    "garminName": "STANDING_ADDUCTION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 1,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-standing-cable-hip-abduction-468",
    "name": "Standing Cable Hip Abduction",
    "polishName": "Odwodzenie bioder z linką wyciągu dolnego stojąc",
    "garminCategory": "HIP_STABILITY",
    "garminName": "STANDING_CABLE_HIP_ABDUCTION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 1,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-standing-hip-abduction-469",
    "name": "Standing Hip Abduction",
    "polishName": "Odwodzenie bioder stojąc",
    "garminCategory": "HIP_STABILITY",
    "garminName": "STANDING_HIP_ABDUCTION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 1,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-standing-rear-leg-raise-470",
    "name": "Standing Rear-leg Raise",
    "polishName": "Wznosy wyprostowanej nogi w tył stojąc",
    "garminCategory": "HIP_STABILITY",
    "garminName": "STANDING_REAR_LEG_RAISE",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 2,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-stability-supine-hip-internal-rotation-471",
    "name": "Supine Hip Internal Rotation",
    "polishName": "Rotacja wewnętrzna biodra w leżeniu tyłem",
    "garminCategory": "HIP_STABILITY",
    "garminName": "SUPINE_HIP_INTERNAL_ROTATION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 1,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  }
] satisfies readonly Exercise[];
