import type { Exercise } from "../exercises";

export const hipRaise = [
  {
    "id": "hip-raise-barbell-hip-thrust-on-floor-407",
    "name": "Barbell Glute Bridge",
    "polishName": "Mostek biodrowy ze sztangą",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-barbell-hip-thrust-with-bench-408",
    "name": "Barbell Hip Thrust with Bench",
    "polishName": "Hip thrust ze sztangą na ławce",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-bridge-with-leg-extension-410",
    "name": "Bridge with Leg Extension",
    "polishName": "Mostek z wyprostem nogi",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "glute-kickback",
    "name": "Glute Kickback",
    "polishName": "Kickback pośladkowy",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-clam-bridge-411",
    "name": "Clam Bridge",
    "polishName": "Mostek z odwodzeniem kolan",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 5,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-front-kick-tabletop-412",
    "name": "Front Kick Tabletop",
    "polishName": "Wykop wprzód w pozycji stołu",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-hip-extension-and-cross-413",
    "name": "Hip Extension and Cross",
    "polishName": "Wyprost biodra z krzyżowaniem nóg",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-hip-raise-414",
    "name": "Hip Raise",
    "polishName": "Wznosy biodra",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-hip-raise-with-knee-squeeze-418",
    "name": "Hip Raise with Knee Squeeze",
    "polishName": "Wznosy biodra ze ściskaniem piłki lekarskiej kolanami",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 4,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-incline-rear-leg-extension-419",
    "name": "Incline Rear-leg Extension",
    "polishName": "Wyprost tylnej nogi w pochyleniu",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-kettlebell-swing-420",
    "name": "Kettlebell Swing",
    "polishName": "Wymachy odważnikiem",
    "category": "HIP_SWING",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 2,
      "shoulders": 2,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 1,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-thrust",
    "name": "Hip Thrust",
    "polishName": "Hip thrust",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 2,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-marching-hip-raise-421",
    "name": "Marching Hip Raise",
    "polishName": "Wznosy biodra w marszu leżąc",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 2,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 2,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hip-raise-reverse-hip-raise-423",
    "name": "Reverse Hip Raise",
    "polishName": "Odwrócone wznosy biodra",
    "category": "HIP_RAISE",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 2,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  }
] satisfies readonly Exercise[];
