import type { Exercise } from "../exercises";

export const olympicLift = [
  {
    "id": "olympic-lift-clean-709",
    "name": "Barbell Clean",
    "polishName": "Zarzut sztangi",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 3,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-barbell-hang-power-clean-699",
    "name": "Barbell Hang Power Clean",
    "polishName": "Energiczny zarzut sztangi z utrzymaniem chwytu",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 3,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-barbell-hang-power-snatch-700",
    "name": "Barbell Hang Power Snatch",
    "polishName": "Energiczne rwanie sztangi z utrzymaniem chwytu",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-barbell-hang-pull-701",
    "name": "Barbell Hang Pull",
    "polishName": "Podciąganie sztangi pod brodę",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 2,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 4,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 3,
      "shoulders": 4,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-barbell-hang-squat-clean-702",
    "name": "Barbell Hang Squat Clean",
    "polishName": "Zarzut sztangi w przysiadzie w zwisie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 3,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "squat-barbell-hang-squat-snatch-1255",
    "name": "Barbell Hang Squat Snatch",
    "polishName": "Rwanie sztangi w przysiadzie w zwisie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-barbell-high-pull-703",
    "name": "Barbell High Pull",
    "polishName": "Podciąganie sztangi",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 2,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 4,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 3,
      "shoulders": 4,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-barbell-power-clean-704",
    "name": "Barbell Power Clean",
    "polishName": "Energiczny zarzut sztangi",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 3,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-barbell-power-snatch-705",
    "name": "Barbell Power Snatch",
    "polishName": "Energiczne rwanie sztangi",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-barbell-snatch-706",
    "name": "Barbell Snatch",
    "polishName": "Rwanie sztangi",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-barbell-split-jerk-707",
    "name": "Barbell Split Jerk",
    "polishName": "Podrzut w rozkroku ze sztangą",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 4,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 4,
      "shoulders": 5,
      "traps": 4,
      "triceps": 4
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-barbell-squat-clean-708",
    "name": "Barbell Squat Clean",
    "polishName": "Zarzut sztangi w przysiadzie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 3,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "squat-barbell-squat-snatch-1259",
    "name": "Barbell Squat Snatch",
    "polishName": "Rwanie sztangi w przysiadzie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-clean-and-jerk-710",
    "name": "Clean and Jerk",
    "polishName": "Zarzut z wybiciem",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 4
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-clean-and-press-711",
    "name": "Clean and Press",
    "polishName": "Zarzut i wyciskanie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 4
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-dumbbell-clean-712",
    "name": "Dumbbell Clean",
    "polishName": "Zarzut hantli",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 3,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-dumbbell-hang-pull-713",
    "name": "Dumbbell Hang Pull",
    "polishName": "Podciąganie hantli pod brodę",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 2,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 4,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 3,
      "shoulders": 4,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-dumbbell-hang-snatch-714",
    "name": "Dumbbell Hang Snatch",
    "polishName": "Rwanie hantla w zwisie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-dumbbell-power-clean-and-jerk-715",
    "name": "Dumbbell Power Clean and Jerk",
    "polishName": "Energiczny zarzut hantli z wybiciem",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 4
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-dumbbell-power-clean-and-push-press-716",
    "name": "Dumbbell Power Clean and Push Press",
    "polishName": "Energiczny zarzut hantli z wyciskaniem",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 4
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-dumbbell-power-clean-and-strict-press-717",
    "name": "Dumbbell Power Clean and Strict Press",
    "polishName": "Energiczny zarzut hantli i wyciskanie bez pomocy nóg",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 4
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-dumbbell-snatch-718",
    "name": "Dumbbell Snatch",
    "polishName": "Rwanie hantla",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "squat-dumbbell-squat-clean-1273",
    "name": "Dumbbell Squat Clean",
    "polishName": "Zarzut hantli w przysiadzie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 3,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "squat-dumbbell-squat-snatch-1274",
    "name": "Dumbbell Squat Snatch",
    "polishName": "Rwanie hantli nad głowę w przysiadzie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-medicine-ball-clean-719",
    "name": "Medicine Ball Clean",
    "polishName": "Zarzut piłką lekarską w przysiadzie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 3,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 1,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-one-hand-dumbbell-split-snatch-720",
    "name": "One-hand Dumbbell Split Snatch",
    "polishName": "Podrywanie hantla jednorącz w rozkroku",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-push-jerk-721",
    "name": "Push Jerk",
    "polishName": "Podrzut",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 4,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 4,
      "shoulders": 5,
      "traps": 4,
      "triceps": 4
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-single-arm-dumbbell-snatch-722",
    "name": "Single-arm Dumbbell Snatch",
    "polishName": "Podrywanie hantla jednorącz",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-single-arm-hang-snatch-723",
    "name": "Single-arm Hang Snatch",
    "polishName": "Rwanie jednorącz w zwisie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-single-arm-kettlebell-snatch-724",
    "name": "Single-arm Kettlebell Snatch",
    "polishName": "Podrywanie odważnika jednorącz",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 1,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-snatch-727",
    "name": "Snatch",
    "polishName": "Rwanie",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 4,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-split-jerk-725",
    "name": "Split Jerk",
    "polishName": "Podrzut w rozkroku",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 4,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 4,
      "shoulders": 5,
      "traps": 4,
      "triceps": 4
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "olympic-lift-squat-clean-and-jerk-726",
    "name": "Squat Clean and Jerk",
    "polishName": "Przysiady z zarzutem i wybiciem",
    "category": "OLYMPIC_LIFT",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 3,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 4,
      "hips": 0,
      "lats": 0,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 5,
      "shoulders": 5,
      "traps": 5,
      "triceps": 4
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  }
] satisfies readonly Exercise[];
