import type { Exercise } from "../exercises";

export const ropeClimb = [
  {
    "id": "lateral-raise-rope-climb-557",
    "name": "Rope Climb",
    "polishName": "Wspinaczka po linie",
    "category": "ROPE_CLIMB",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 5,
      "calves": 0,
      "chest": 0,
      "forearm": 5,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 2,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 4,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 1,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  }
] satisfies readonly Exercise[];
