import type { Exercise } from "../exercises";

export const row = [
  {
    "id": "row-barbell-row-1034",
    "name": "Barbell Row",
    "polishName": "Wiosłowanie sztangą",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 5,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-barbell-straight-leg-deadlift-to-row-1035",
    "name": "Barbell Straight-leg Deadlift to Row",
    "polishName": "Martwy ciąg ze sztangą na wyprostowanych nogach z wiosłowaniem",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 3,
      "glutes": 5,
      "hamstrings": 5,
      "hips": 0,
      "lats": 5,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-bent-over-row-with-barbell-1036",
    "name": "Bent-over Row with Barbell",
    "polishName": "Wiosłowanie sztangą trzymaną nachwytem do klatki w opadzie tułowia",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 5,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-bent-over-row-with-dumbell-1037",
    "name": "Bent-over Row with Dumbbell",
    "polishName": "Wiosłowanie hantlami trzymanymi nachwytem do klatki w opadzie tułowia",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 5,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-cable-row-standing-1038",
    "name": "Cable Row Standing",
    "polishName": "Wiosłowanie z linką wyciągu dolnego stojąc",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 1,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-chest-supported-dumbbell-row-1039",
    "name": "Chest Supported Dumbbell Row",
    "polishName": "Wiosłowanie hantlami w oparciu o ławkę dodatnią",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "chest-supported-machine-row",
    "name": "Chest Supported Machine Row",
    "polishName": "Wiosłowanie na maszynie z podparciem klatki",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-decline-ring-row-1040",
    "name": "Decline Ring Row",
    "polishName": "Wiosłowanie na kółkach gimnastycznych w opadzie ze stopami na podwyższeniu",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 1,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-dumbbell-row-1041",
    "name": "Dumbbell Row",
    "polishName": "Wiosłowanie hantlami",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-elevated-ring-row-1043",
    "name": "Elevated Ring Row",
    "polishName": "Wiosłowanie na kółkach gimnastycznych ze stopami na podwyższeniu",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 1,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-elevated-feet-inverted-row-1042",
    "name": "Elevated-feet Inverted Row",
    "polishName": "Odwrócone wiosłowanie z uniesionymi stopami",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 1,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-face-pull-1044",
    "name": "Face Pull",
    "polishName": "Face pull na wyciągu",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 2,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 1,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-face-pull-with-external-rotation-1045",
    "name": "Face Pull with External Rotation",
    "polishName": "Face pull na wyciągu z rotacją zewnętrzną",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 2,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 1,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 5,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "rehab"
  },
  {
    "id": "row-inverted-row-1047",
    "name": "Inverted Row",
    "polishName": "Odwrócone wiosłowanie",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 1,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-kettlebell-row-1049",
    "name": "Kettlebell Row",
    "polishName": "Wiosłowanie z odważnikiem",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 1,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "hyperextension-lat-pull-down-with-row-500",
    "name": "Lat Pull-down with Row",
    "polishName": "Ściąganie drążka wyciągu z wiosłowaniem",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "machine-row",
    "name": "Machine Row",
    "polishName": "Wiosłowanie na maszynie",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-modified-inverted-row-1050",
    "name": "Modified Inverted Row",
    "polishName": "Zmodyfikowane wiosłowanie odwrócone",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 1,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-renegade-row-1054",
    "name": "Renegade Row",
    "polishName": "Wiosłowanie renegata",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 5,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 2,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 4,
      "quads": 1,
      "shoulders": 4,
      "traps": 4,
      "triceps": 3
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-reverse-grip-barbell-row-1055",
    "name": "Reverse-grip Barbell Row",
    "polishName": "Wiosłowanie sztangą podchwytem",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 4,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 2,
      "hamstrings": 2,
      "hips": 0,
      "lats": 5,
      "lowerBack": 4,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "row-ring-row-1056",
    "name": "Ring Row",
    "polishName": "Wiosłowanie na kółkach gimnastycznych",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 1,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-rope-handle-cable-row-1057",
    "name": "Rope-handle Cable Row",
    "polishName": "Wiosłowanie z linką wyciągu dolnego",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-seated-cable-row-1059",
    "name": "Seated Cable Row",
    "polishName": "Wiosłowanie siedząc na wyciągu",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-seated-dumbbell-row-1060",
    "name": "Seated Dumbbell Row",
    "polishName": "Wiosłowanie hantlami siedząc",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-seated-underhand-grip-cable-row-1061",
    "name": "Seated Underhand-grip Cable Row",
    "polishName": "Wiosłowanie z linką wyciągu dolnego podchwytem siedząc",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 4,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-t-bar-row-1068",
    "name": "T-Bar Row",
    "polishName": "Wiosłowanie sztangą T-bar",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 3,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 1,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-underhand-grip-cable-row-1071",
    "name": "Underhand-grip Cable Row",
    "polishName": "Wiosłowanie z linką wyciągu dolnego podchwytem",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 4,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-v-grip-cable-row-1072",
    "name": "V-grip Cable Row",
    "polishName": "Wiosłowanie z linką wyciągu dolnego w chwycie neutralnym",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 5,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 4,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "row-wide-grip-seated-cable-row-1082",
    "name": "Wide-grip Seated Cable Row",
    "polishName": "Wiosłowanie z linką wyciągu dolnego w chwycie szerokim siedząc",
    "category": "ROW",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 3,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 4,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 4,
      "traps": 5,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  }
] satisfies readonly Exercise[];
