import type { Exercise } from "../exercises";

export const shoulderPress = [
  {
    "id": "shoulder-press-alternating-dumbbell-shoulder-press-1110",
    "name": "Alternating Dumbbell Shoulder Press",
    "polishName": "Naprzemienne wyciskanie hantli (żołnierskie)",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "ALTERNATING_DUMBBELL_SHOULDER_PRESS",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/SHOULDER_PRESS/ALTERNATING_DUMBBELL_SHOULDER_PRESS",
    "difficulty": "Intermediate",
    "description": "The alternating dumbbell shoulder press increases muscular strength through the entire shoulder region. Performing the exercise in an alternating manner will create balance and stability on both sides of the body while actively engaging the core.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-arnold-press-1111",
    "name": "Arnold Press",
    "polishName": "Wyciskanie hantli — „arnoldki”",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "ARNOLD_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-barbell-front-squat-to-push-press-1112",
    "name": "Barbell Front Squat to Push Press",
    "polishName": "Przysiady przednie z wyciskaniem sztangi",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "BARBELL_FRONT_SQUAT_TO_PUSH_PRESS",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/SHOULDER_PRESS/BARBELL_FRONT_SQUAT_TO_PUSH_PRESS",
    "difficulty": "Advanced",
    "description": "The barbell front squat to push press is a full body strength exercise that targets the shoulders and legs. This exercise also greatly increases core strength and stability.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 2,
      "chest": 2,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 2,
      "hips": 2,
      "lats": 0,
      "lowerBack": 2,
      "obliques": 0,
      "quads": 1,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-overhead-barbell-press-1125",
    "name": "Barbell Overhead Press",
    "polishName": "Wyciskanie sztangi nad głowę",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "OVERHEAD_BARBELL_PRESS",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/SHOULDER_PRESS/OVERHEAD_BARBELL_PRESS",
    "difficulty": "Beginner",
    "description": "The overhead barbell press increases upper body strength, specifically in the shoulders and triceps. The movement also improves core stability.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-barbell-push-press-1113",
    "name": "Barbell Push Press",
    "polishName": "Wyciskanie sztangi nad głowę z ugiętymi kolanami",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "BARBELL_PUSH_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-dumbbell-alternating-shoulder-press-and-twist-1116",
    "name": "Dumbbell Alternating Shoulder Press and Twist",
    "polishName": "Naprzemienne wyciskanie hantli ze skrętem (żołnierskie)",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "DUMBBELL_ALTERNATING_SHOULDER_PRESS_AND_TWIST",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-dumbbell-push-press-1119",
    "name": "Dumbbell Push Press",
    "polishName": "Wyciskanie hantli nad głowę z wybiciem z nóg",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "DUMBBELL_PUSH_PRESS",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/SHOULDER_PRESS/DUMBBELL_PUSH_PRESS",
    "difficulty": "Advanced",
    "description": "The dumbbell push press is a multi-joint exercise that increases strength and power throughout the entire body, with an emphasis on the shoulders and triceps. The use of dumbbells improves balance and stability on each side.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-overhead-dumbbell-press-1126",
    "name": "Dumbbell Shoulder Press",
    "polishName": "Wyciskanie hantli nad głowę",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "OVERHEAD_DUMBBELL_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-floor-inverted-shoulder-press-1121",
    "name": "Floor Inverted Shoulder Press",
    "polishName": "Pompki na barki na podłodze",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "FLOOR_INVERTED_SHOULDER_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 1,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-inverted-shoulder-press-1122",
    "name": "Inverted Shoulder Press",
    "polishName": "Pompki na barki na podwyższeniu",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "INVERTED_SHOULDER_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 1,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "machine-shoulder-press",
    "name": "Machine Shoulder Press",
    "polishName": "Wyciskanie barków na maszynie",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "MACHINE_SHOULDER_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "Beginner",
    "description": "A basic overhead press variation for users who prefer a stable movement path.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 1,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 1,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-one-arm-push-press-1124",
    "name": "One-arm Push Press",
    "polishName": "Wyciskanie hantla jednorącz",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "ONE_ARM_PUSH_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-seated-barbell-shoulder-press-1127",
    "name": "Seated Barbell Shoulder Press",
    "polishName": "Wyciskanie sztangi siedząc (żołnierskie)",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "SEATED_BARBELL_SHOULDER_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-seated-dumbbell-shoulder-press-1128",
    "name": "Seated Dumbbell Shoulder Press",
    "polishName": "Wyciskanie hantli siedząc (żołnierskie)",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "SEATED_DUMBBELL_SHOULDER_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-single-arm-dumbbell-shoulder-press-1129",
    "name": "Single-arm Dumbbell Shoulder Press",
    "polishName": "Wyciskanie hantla jednorącz (żołnierskie)",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "SINGLE_ARM_DUMBBELL_SHOULDER_PRESS",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/SHOULDER_PRESS/SINGLE_ARM_DUMBBELL_SHOULDER_PRESS",
    "difficulty": "Intermediate",
    "description": "The single-arm dumbbell shoulder press is a unilateral exercise that increases shoulder strength, stability, and symmetry. Performing the exercise with one arm at a time will actively engage the core throughout the range of motion.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-single-arm-step-up-and-press-1130",
    "name": "Single-arm Step-up and Press",
    "polishName": "Wyciskanie hantla jednorącz z wejściem na podwyższenie",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "SINGLE_ARM_STEP_UP_AND_PRESS",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/SHOULDER_PRESS/SINGLE_ARM_STEP_UP_AND_PRESS",
    "difficulty": "Intermediate",
    "description": "The single-arm step-up and press builds strength in the lower-body and shoulder area. Isolating one arm at a time also improves balance and stability.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 2,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 1,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 1,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-smith-machine-overhead-press-1131",
    "name": "Smith Machine Overhead Press",
    "polishName": "Wyciskanie nad głowę na maszynie Smitha",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "SMITH_MACHINE_OVERHEAD_PRESS",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/SHOULDER_PRESS/SMITH_MACHINE_OVERHEAD_PRESS",
    "difficulty": "Beginner",
    "description": "The Smith machine overhead press helps increase strength and muscle growth throughout the entire shoulder region. The range of motion of the Smith machine assists beginners with learning the movement pattern.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 1,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-split-stance-hammer-curl-to-press-1132",
    "name": "Split-stance Hammer Curl to Press",
    "polishName": "Uginanie hantli w chwycie młotkowym z wyciskaniem w wykroku",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "SPLIT_STANCE_HAMMER_CURL_TO_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 1,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "shoulder-press-swiss-ball-dumbbell-shoulder-press-1134",
    "name": "Swiss Ball Dumbbell Shoulder Press",
    "polishName": "Wyciskanie hantli na piłce gimnastycznej (żołnierskie)",
    "garminCategory": "SHOULDER_PRESS",
    "garminName": "SWISS_BALL_DUMBBELL_SHOULDER_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 2,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "advanced"
  }
] satisfies readonly Exercise[];
