import type { Exercise } from "../exercises";

export const stairStepper = [
  {
    "id": "stair-stepper-stair-stepper-1344",
    "name": "Stair Stepper",
    "polishName": "Stepper",
    "garminCategory": "STAIR_STEPPER",
    "garminName": "STAIR_STEPPER",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 1,
      "hamstrings": 2,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 1,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  }
] satisfies readonly Exercise[];
