import type { Exercise } from "../exercises";

export const stepUp = [
  {
    "id": "squat-barbell-lateral-step-up-1256",
    "name": "Barbell Lateral Step-up",
    "polishName": "Wchodzenie boczne na podwyższenie ze sztangą na barkach",
    "category": "STEP_UP",
    "muscleImpact": {
      "abductors": 4,
      "abs": 1,
      "adductors": 2,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 4,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 1,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "squat-barbell-stepover-1262",
    "name": "Barbell Step-over",
    "polishName": "Przechodzenie ze sztangą na barkach przez podwyższenie",
    "category": "STEP_UP",
    "muscleImpact": {
      "abductors": 2,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 4,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 5,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 1,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "squat-barbell-step-up-1261",
    "name": "Barbell Step-up",
    "polishName": "Wchodzenie ze sztangą na barkach na podwyższenie",
    "category": "STEP_UP",
    "muscleImpact": {
      "abductors": 2,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 4,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 5,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 1,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "squat-crossover-dumbbell-step-up-1268",
    "name": "Crossover Dumbbell Step-up",
    "polishName": "Obustronne wchodzenie na podwyższenie z hantlami bokiem",
    "category": "STEP_UP",
    "muscleImpact": {
      "abductors": 4,
      "abs": 1,
      "adductors": 2,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 4,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 1,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "squat-dumbbell-stepover-1276",
    "name": "Dumbbell Step-over",
    "polishName": "Przechodzenie z hantlami przez podwyższenie",
    "category": "STEP_UP",
    "muscleImpact": {
      "abductors": 2,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 4,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 5,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 1,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "squat-dumbbell-step-up-1275",
    "name": "Dumbbell Step-up",
    "polishName": "Wchodzenie na podwyższenie z hantlami",
    "category": "STEP_UP",
    "muscleImpact": {
      "abductors": 2,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 4,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 5,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 1,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "squat-lateral-dumbbell-step-up-1284",
    "name": "Lateral Dumbbell Step-up",
    "polishName": "Wchodzenie boczne z hantlami na podwyższenie",
    "category": "STEP_UP",
    "muscleImpact": {
      "abductors": 4,
      "abs": 1,
      "adductors": 2,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 4,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 1,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "leg-raise-lateral-stepover-589",
    "name": "Lateral Step-over",
    "polishName": "Przechodzenie bokiem nad podwyższeniem",
    "category": "STEP_UP",
    "muscleImpact": {
      "abductors": 4,
      "abs": 1,
      "adductors": 2,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 5,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 4,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "squat-step-up-1305",
    "name": "Step-up",
    "polishName": "Wchodzenie na podwyższenie",
    "category": "STEP_UP",
    "muscleImpact": {
      "abductors": 2,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 2,
      "chest": 0,
      "forearm": 0,
      "glutes": 4,
      "hamstrings": 3,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 5,
      "shoulders": 0,
      "traps": 0,
      "triceps": 0
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 1,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  }
] satisfies readonly Exercise[];
