import type { Exercise } from "../exercises";

export const tricepsExtension = [
  {
    "id": "triceps-extension-alternating-dumbbell-lying-triceps-extension-1398",
    "name": "Alternating Dumbbell Lying Triceps Extension",
    "polishName": "Naprzemienne prostowanie tricepsów nad głową z hantlami leżąc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-bench-dip-1399",
    "name": "Bench Dip",
    "polishName": "Dipy na ławce",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-body-weight-dip-1400",
    "name": "Body-weight Dip",
    "polishName": "Dipy (bez obciążenia)",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-cable-lying-triceps-extension-1402",
    "name": "Cable Lying Triceps Extension",
    "polishName": "Wyprost tricepsów nad głową na wyciągu leżąc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-cable-overhead-triceps-extension-1403",
    "name": "Cable Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów na wyciągu nad głowę",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-cable-kickback-1401",
    "name": "Cable Tricep Kick-back",
    "polishName": "Prostowanie tricepsa na wyciągu",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-dumbbell-lying-triceps-extension-1405",
    "name": "Dumbbell Lying Triceps Extension",
    "polishName": "Wyprost tricepsów z hantlami nad głową leżąc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-dumbbell-kickback-1404",
    "name": "Dumbbell Triceps Kickback",
    "polishName": "Prostowanie ramienia z hantlem w opadzie tułowia",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-ez-bar-overhead-triceps-extension-1406",
    "name": "EZ-Bar Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą łamaną nad głowę",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-incline-dip-1407",
    "name": "Incline Dip",
    "polishName": "Dipy na poręczach",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-incline-ez-bar-lying-triceps-extension-1408",
    "name": "Incline EZ-Bar Lying Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą łamaną nad głową na ławce dodatniej",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "lateral-raise-ring-dip-kipping-555",
    "name": "Kipping Ring Dip",
    "polishName": "Dipy na kółkach gimnastycznych z kippingiem",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 2,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 1,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "triceps-extension-lying-dumbbell-pullover-to-extension-1409",
    "name": "Lying Dumbbell Pull-over to Extension",
    "polishName": "Ściąganie hantla do wyprostu ramion leżąc na ławce prostej",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 4,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-lying-ez-bar-triceps-extension-1410",
    "name": "Lying EZ-Bar Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą łamaną nad głową leżąc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-lying-triceps-extension-to-close-grip-bench-press-1411",
    "name": "Lying Triceps Extension to Close-grip Bench Press",
    "polishName": "Wyprost tricepsów z przejściem do wyciskania sztangi w chwycie wąskim na ławce",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-overhead-dumbbell-triceps-extension-1412",
    "name": "Overhead Dumbbell Triceps Extension",
    "polishName": "Wyprost tricepsów z hantlem nad głowę",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-reclining-triceps-press-1413",
    "name": "Reclining Triceps Press",
    "polishName": "Wyciskanie tricepsów półleżąc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-reverse-grip-triceps-pressdown-1415",
    "name": "Reverse-grip Triceps Press-down",
    "polishName": "Prostowanie ramion na wyciągu podchwytem",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "lateral-raise-ring-dip-554",
    "name": "Ring Dip",
    "polishName": "Dipy na kółkach gimnastycznych",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 2,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 1,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-rope-pressdown-1416",
    "name": "Rope Press-down",
    "polishName": "Wyciskanie z linką wyciągu górnego nachwytem",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-seated-barbell-overhead-triceps-extension-1417",
    "name": "Seated Barbell Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą nad głowę siedząc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-seated-dumbbell-overhead-triceps-extension-1418",
    "name": "Seated Dumbbell Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów z hantlem nad głowę siedząc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-seated-ez-bar-overhead-triceps-extension-1419",
    "name": "Seated EZ-Bar Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą łamaną nad głowę siedząc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-seated-single-arm-overhead-dumbbell-extension-1420",
    "name": "Seated Single-arm Overhead Dumbbell Extension",
    "polishName": "Podnoszenie jednorącz hantla nad głowę siedząc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-single-arm-dumbbell-overhead-triceps-extension-1421",
    "name": "Single-arm Dumbbell Overhead Triceps Extension",
    "polishName": "Wyprost jednorącz tricepsa z hantlem nad głowę",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-single-dumbbell-seated-overhead-triceps-extension-1422",
    "name": "Single-dumbbell Seated Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów z jednym hantlem nad głowę siedząc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-single-leg-bench-dip-and-kick-1423",
    "name": "Single-leg Bench Dip and Kick",
    "polishName": "Dipy na ławce jednonóż z kopnięciem",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-single-leg-dip-1424",
    "name": "Single-leg Dip",
    "polishName": "Dipy jednonóż",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-static-lying-triceps-extension-1425",
    "name": "Static Lying Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą nad głową z przytrzymaniem leżąc",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-suspended-dip-1426",
    "name": "Suspended Dip",
    "polishName": "Dipy na poręczach w zawieszeniu",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 3,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 2,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 1,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-swiss-ball-dumbbell-lying-triceps-extension-1427",
    "name": "Swiss Ball Dumbbell Lying Triceps Extension",
    "polishName": "Wyprost tricepsów z hantlami nad głową leżąc na piłce gimnastycznej",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-swiss-ball-dumbbell-overhead-triceps-extension-367",
    "name": "Swiss Ball Dumbbell Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów z hantlami nad głowę na piłce gimnastycznej",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-swiss-ball-ez-bar-lying-triceps-extension-1428",
    "name": "Swiss Ball EZ-Bar Lying Triceps Extension",
    "polishName": "Wyprost tricepsów nad głową ze sztangą łamaną leżąc na piłce gimnastycznej.",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-swiss-ball-ez-bar-overhead-triceps-extension-1429",
    "name": "Swiss Ball EZ-Bar Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą łamaną nad głowę na piłce gimnastycznej",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-tabletop-dip-1430",
    "name": "Tabletop Dip",
    "polishName": "Pompki tyłem w pozycji stołu",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-triceps-extension-on-floor-1431",
    "name": "Triceps Extension on Floor",
    "polishName": "Wyprost tricepsów nad głową na podłodze",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-triceps-press-1432",
    "name": "Triceps Press",
    "polishName": "Wyciskanie tricepsów",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-triceps-pressdown-1433",
    "name": "Triceps Press-down",
    "polishName": "Wyciskanie tricepsów z linką wyciągu górnego nachwytem",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 1,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-weighted-dip-1435",
    "name": "Weighted Dip",
    "polishName": "Dipy (z obciążeniem)",
    "category": "TRICEPS_EXTENSION",
    "muscleImpact": {
      "abductors": 0,
      "abs": 1,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 4,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 3,
      "traps": 0,
      "triceps": 5
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 1,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  }
] satisfies readonly Exercise[];
