import type { Exercise } from "../exercises";

export const tricepsExtension = [
  {
    "id": "triceps-extension-alternating-dumbbell-lying-triceps-extension-1398",
    "name": "Alternating Dumbbell Lying Triceps Extension",
    "polishName": "Naprzemienne prostowanie tricepsów nad głową z hantlami leżąc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "ALTERNATING_DUMBBELL_LYING_TRICEPS_EXTENSION",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/ALTERNATING_DUMBBELL_LYING_TRICEPS_EXTENSION",
    "difficulty": "Intermediate",
    "description": "The alternating dumbbell triceps extension is an isolating single-joint exercise used to increase size and strength throughout the triceps.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-bench-dip-1399",
    "name": "Bench Dip",
    "polishName": "Dipy na ławce",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "BENCH_DIP",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-body-weight-dip-1400",
    "name": "Body-weight Dip",
    "polishName": "Dipy (bez obciążenia)",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "BODY_WEIGHT_DIP",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-cable-lying-triceps-extension-1402",
    "name": "Cable Lying Triceps Extension",
    "polishName": "Wyprost tricepsów nad głową na wyciągu leżąc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "CABLE_LYING_TRICEPS_EXTENSION",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/CABLE_LYING_TRICEPS_EXTENSION",
    "difficulty": "Intermediate",
    "description": "The cable lying triceps extension is an isolation exercise that strengthens the triceps.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-cable-overhead-triceps-extension-1403",
    "name": "Cable Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów na wyciągu nad głowę",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "CABLE_OVERHEAD_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-cable-kickback-1401",
    "name": "Cable Tricep Kick-back",
    "polishName": "Prostowanie tricepsa na wyciągu",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "CABLE_KICKBACK",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-dumbbell-lying-triceps-extension-1405",
    "name": "Dumbbell Lying Triceps Extension",
    "polishName": "Wyprost tricepsów z hantlami nad głową leżąc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "DUMBBELL_LYING_TRICEPS_EXTENSION",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/DUMBBELL_LYING_TRICEPS_EXTENSION",
    "difficulty": "Beginner",
    "description": "Dumbbell lying triceps extensions increase strength in the triceps. Performing the exercise with dumbbells will achieve muscular balance on both sides of the body.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-dumbbell-kickback-1404",
    "name": "Dumbbell Triceps Kickback",
    "polishName": "Prostowanie ramienia z hantlem w opadzie tułowia",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "DUMBBELL_KICKBACK",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/DUMBBELL_KICKBACK",
    "difficulty": "Beginner",
    "description": "This is a single-joint isolating exercise that targets the back of the upper arm while developing stability throughout the hand and wrist region.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-ez-bar-overhead-triceps-extension-1406",
    "name": "EZ-Bar Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą łamaną nad głowę",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "EZ_BAR_OVERHEAD_TRICEPS_EXTENSION",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/EZ_BAR_OVERHEAD_TRICEPS_EXTENSION",
    "difficulty": "Beginner",
    "description": "The EZ-Bar overhead triceps extensions increase strength in the triceps while building stability in the shoulders. The EZ-Bar provides favorable hand positioning for easing strain on the wrists and elbows. It also allows for a greater range of motion on the lower portion, which stretches the triceps and allows for more muscle growth.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-incline-dip-1407",
    "name": "Incline Dip",
    "polishName": "Dipy na poręczach",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "INCLINE_DIP",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/INCLINE_DIP",
    "difficulty": "Intermediate",
    "description": "The incline dip is a variation of the body-weight dip that strengthens the chest, shoulders, and triceps with less strain placed on the shoulder joints.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 1,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 2
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-incline-ez-bar-lying-triceps-extension-1408",
    "name": "Incline EZ-Bar Lying Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą łamaną nad głową na ławce dodatniej",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "INCLINE_EZ_BAR_LYING_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "lateral-raise-ring-dip-kipping-555",
    "name": "Kipping Ring Dip",
    "polishName": "Dipy na kółkach gimnastycznych z kippingiem",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "RING_DIP_KIPPING",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 1,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "sportSpecific"
  },
  {
    "id": "triceps-extension-lying-dumbbell-pullover-to-extension-1409",
    "name": "Lying Dumbbell Pull-over to Extension",
    "polishName": "Ściąganie hantla do wyprostu ramion leżąc na ławce prostej",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "LYING_DUMBBELL_PULLOVER_TO_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-lying-ez-bar-triceps-extension-1410",
    "name": "Lying EZ-Bar Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą łamaną nad głową leżąc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "LYING_EZ_BAR_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-lying-triceps-extension-to-close-grip-bench-press-1411",
    "name": "Lying Triceps Extension to Close-grip Bench Press",
    "polishName": "Wyprost tricepsów z przejściem do wyciskania sztangi w chwycie wąskim na ławce",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "LYING_TRICEPS_EXTENSION_TO_CLOSE_GRIP_BENCH_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-overhead-dumbbell-triceps-extension-1412",
    "name": "Overhead Dumbbell Triceps Extension",
    "polishName": "Wyprost tricepsów z hantlem nad głowę",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "OVERHEAD_DUMBBELL_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-reclining-triceps-press-1413",
    "name": "Reclining Triceps Press",
    "polishName": "Wyciskanie tricepsów półleżąc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "RECLINING_TRICEPS_PRESS",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-reverse-grip-triceps-pressdown-1415",
    "name": "Reverse-grip Triceps Press-down",
    "polishName": "Prostowanie ramion na wyciągu podchwytem",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "REVERSE_GRIP_TRICEPS_PRESSDOWN",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "lateral-raise-ring-dip-554",
    "name": "Ring Dip",
    "polishName": "Dipy na kółkach gimnastycznych",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "RING_DIP",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 1,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-rope-pressdown-1416",
    "name": "Rope Press-down",
    "polishName": "Wyciskanie z linką wyciągu górnego nachwytem",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "ROPE_PRESSDOWN",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/ROPE_PRESSDOWN",
    "difficulty": "Beginner",
    "description": "The rope pressdown is a single-joint isolation exercise that builds strength and muscular endurance through the triceps muscle.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 2,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-seated-barbell-overhead-triceps-extension-1417",
    "name": "Seated Barbell Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą nad głowę siedząc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SEATED_BARBELL_OVERHEAD_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 1,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-seated-dumbbell-overhead-triceps-extension-1418",
    "name": "Seated Dumbbell Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów z hantlem nad głowę siedząc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SEATED_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-seated-ez-bar-overhead-triceps-extension-1419",
    "name": "Seated EZ-Bar Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą łamaną nad głowę siedząc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SEATED_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-seated-single-arm-overhead-dumbbell-extension-1420",
    "name": "Seated Single-arm Overhead Dumbbell Extension",
    "polishName": "Podnoszenie jednorącz hantla nad głowę siedząc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SEATED_SINGLE_ARM_OVERHEAD_DUMBBELL_EXTENSION",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/SEATED_SINGLE_ARM_OVERHEAD_DUMBBELL_EXTENSION",
    "difficulty": "Intermediate",
    "description": "The seated single-arm overhead dumbbell extension is an isolation exercise that strengthens the triceps. This exercise also improves shoulder stability and mobility. The seated, overhead position ensures maximum isolation on the target area.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-single-arm-dumbbell-overhead-triceps-extension-1421",
    "name": "Single-arm Dumbbell Overhead Triceps Extension",
    "polishName": "Wyprost jednorącz tricepsa z hantlem nad głowę",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SINGLE_ARM_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-single-dumbbell-seated-overhead-triceps-extension-1422",
    "name": "Single-dumbbell Seated Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów z jednym hantlem nad głowę siedząc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SINGLE_DUMBBELL_SEATED_OVERHEAD_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-single-leg-bench-dip-and-kick-1423",
    "name": "Single-leg Bench Dip and Kick",
    "polishName": "Dipy na ławce jednonóż z kopnięciem",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SINGLE_LEG_BENCH_DIP_AND_KICK",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 2,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-single-leg-dip-1424",
    "name": "Single-leg Dip",
    "polishName": "Dipy jednonóż",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SINGLE_LEG_DIP",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/SINGLE_LEG_DIP",
    "difficulty": "Intermediate",
    "description": "The single-leg dip is a more difficult variation to the standard dip. Using only one leg for support increases the resistance placed on the upper body during the movement. The movement specifically targets the chest, shoulders and triceps.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 2,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 2,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-static-lying-triceps-extension-1425",
    "name": "Static Lying Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą nad głową z przytrzymaniem leżąc",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "STATIC_LYING_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-suspended-dip-1426",
    "name": "Suspended Dip",
    "polishName": "Dipy na poręczach w zawieszeniu",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SUSPENDED_DIP",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 1,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-swiss-ball-dumbbell-lying-triceps-extension-1427",
    "name": "Swiss Ball Dumbbell Lying Triceps Extension",
    "polishName": "Wyprost tricepsów z hantlami nad głową leżąc na piłce gimnastycznej",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SWISS_BALL_DUMBBELL_LYING_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "curl-swiss-ball-dumbbell-overhead-triceps-extension-367",
    "name": "Swiss Ball Dumbbell Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów z hantlami nad głowę na piłce gimnastycznej",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SWISS_BALL_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-swiss-ball-ez-bar-lying-triceps-extension-1428",
    "name": "Swiss Ball EZ-Bar Lying Triceps Extension",
    "polishName": "Wyprost tricepsów nad głową ze sztangą łamaną leżąc na piłce gimnastycznej.",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SWISS_BALL_EZ_BAR_LYING_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-swiss-ball-ez-bar-overhead-triceps-extension-1429",
    "name": "Swiss Ball EZ-Bar Overhead Triceps Extension",
    "polishName": "Wyprost tricepsów ze sztangą łamaną nad głowę na piłce gimnastycznej",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "SWISS_BALL_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 1,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 1,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "variation"
  },
  {
    "id": "triceps-extension-tabletop-dip-1430",
    "name": "Tabletop Dip",
    "polishName": "Pompki tyłem w pozycji stołu",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "TABLETOP_DIP",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 1,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-triceps-extension-on-floor-1431",
    "name": "Triceps Extension on Floor",
    "polishName": "Wyprost tricepsów nad głową na podłodze",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "TRICEPS_EXTENSION_ON_FLOOR",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/TRICEPS_EXTENSION_ON_FLOOR",
    "difficulty": "Beginner",
    "description": "This exercise increases strength and muscle growth in the triceps. Positioning yourself on the floor allows for increased stability throughout the movement.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 1,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-triceps-press-1432",
    "name": "Triceps Press",
    "polishName": "Wyciskanie tricepsów",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "TRICEPS_PRESS",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/TRICEPS_PRESS",
    "difficulty": "Intermediate",
    "description": "This exercise is designed to strengthen the triceps and open the chest.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 2,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 2,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-triceps-pressdown-1433",
    "name": "Triceps Press-down",
    "polishName": "Wyciskanie tricepsów z linką wyciągu górnego nachwytem",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "TRICEPS_PRESSDOWN",
    "foundInGarmin": true,
    "image": "",
    "url": "https://connect.garmin.com/modern/exercises/TRICEPS_EXTENSION/TRICEPS_PRESSDOWN",
    "difficulty": "Beginner",
    "description": "Triceps pressdown is an isolation exercise that increases the strength and size of the triceps while also engaging the front of the shoulders.",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 0,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 0,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 1,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 0,
      "medicineBall": 0,
      "other": 0,
      "plate": 0,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  },
  {
    "id": "triceps-extension-weighted-dip-1435",
    "name": "Weighted Dip",
    "polishName": "Dipy (z obciążeniem)",
    "garminCategory": "TRICEPS_EXTENSION",
    "garminName": "WEIGHTED_DIP",
    "foundInGarmin": false,
    "image": "",
    "url": "",
    "difficulty": "",
    "description": "",
    "muscleImpact": {
      "abductors": 0,
      "abs": 0,
      "adductors": 0,
      "biceps": 0,
      "calves": 0,
      "chest": 2,
      "forearm": 0,
      "glutes": 0,
      "hamstrings": 0,
      "hips": 0,
      "lats": 0,
      "lowerBack": 0,
      "obliques": 0,
      "quads": 0,
      "shoulders": 2,
      "traps": 0,
      "triceps": 1
    },
    "equipment": {
      "ankleWeight": 0,
      "band": 0,
      "barbell": 0,
      "battleRope": 0,
      "bench": 0,
      "bike": 0,
      "bosuBall": 0,
      "box": 0,
      "cableMachine": 0,
      "dumbbell": 0,
      "ezBar": 0,
      "foamRoller": 0,
      "jumpRope": 0,
      "kettlebell": 0,
      "machine": 1,
      "medicineBall": 0,
      "other": 0,
      "plate": 1,
      "pullupBar": 0,
      "rings": 0,
      "rope": 0,
      "sandbag": 0,
      "sled": 0,
      "slidingDisc": 0,
      "smithMachine": 0,
      "squatRack": 0,
      "swissBall": 0,
      "trx": 0,
      "weightVest": 0
    },
    "libraryTier": "main"
  }
] satisfies readonly Exercise[];
